#! /bin/sh
#*******************************************************************************
#
# "@(#) $Id: laserguiStartup,v 1.3 2005/06/22 14:27:45 gchiozzi Exp $"
#
# who       when      what
# --------  --------  ----------------------------------------------
# almadev 2005-06-21 created
#

#************************************************************************
#   NAME
# 
#   SYNOPSIS
# 
#   DESCRIPTION
#
#   FILES
#
#   ENVIRONMENT
#
#   RETURN VALUES
#
#   CAUTIONS
#
#   EXAMPLES
#
#   SEE ALSO
#
#   BUGS     
#
#------------------------------------------------------------------------
#

####### WARNING #####################################
# This is an all-hardcoded prototype startup script #
#####################################################

## Complete list
##  $INTROOT/lib/AbsoluteLayout.jar
##  $INTROOT/lib/acsjms.jar
##  $INTROOT/lib/ACSJMSMessageEntity.jar
##  $INTROOT/lib/AlarmService.jar
##  $INTROOT/lib/alarmsysteminterface.jar
##  $INTROOT/lib/boot.jar
##  $INTROOT/lib/cmwmom.jar
##  $INTROOT/lib/core.jar
##  $INTROOT/lib/core-windows.jar
##  $INTROOT/lib/gp.jar
##  $INTROOT/lib/gpopenide.jar
##  $INTROOT/lib/jms.jar
##  $INTROOT/lib/laserclient.jar
##  $INTROOT/lib/laserconsole.jar
##  $INTROOT/lib/lasercore.jar
##  $INTROOT/lib/laserdefinition.jar
##  $INTROOT/lib/laserguiplatform.jar
##  $INTROOT/lib/laserutil.jar
##  $INTROOT/lib/mail.jar
##  $INTROOT/lib/openide-io.jar
##  $INTROOT/lib/openide.jar
##  

#export CLASSPATH=$INTROOT/lib/AbsoluteLayout.jar:$INTROOT/lib/acsjms.jar:$INTROOT/lib/ACSJMSMessageEntity.jar:$INTROOT/lib/AlarmService.jar:$INTROOT/lib/alarmsysteminterface.jar:$INTROOT/lib/boot.jar:$INTROOT/lib/cmwmom.jar:$INTROOT/lib/core.jar:$INTROOT/lib/core-windows.jar:$INTROOT/lib/gp.jar:$INTROOT/lib/gpopenide.jar:$INTROOT/lib/jms.jar:$INTROOT/lib/laserclient.jar:$INTROOT/lib/laserconsole.jar:$INTROOT/lib/lasercore.jar:$INTROOT/lib/laserdefinition.jar:$INTROOT/lib/laserguiplatform.jar:$INTROOT/lib/laserutil.jar:$INTROOT/lib/mail.jar:$INTROOT/lib/openide-io.jar:$INTROOT/lib/openide.jar:$ACSROOT/lib/log4j-1.2.8.jar:$CLASSPATH

#export CLASSPATH=$INTROOT/lib/AbsoluteLayout.jar:$INTROOT/lib/acsjms.jar:$INTROOT/lib/ACSJMSMessageEntity.jar:$INTROOT/lib/AlarmService.jar:$INTROOT/lib/alarmsysteminterface.jar:$INTROOT/lib/boot.jar:$INTROOT/lib/cmwmom.jar:$INTROOT/lib/gp.jar:$INTROOT/lib/jms.jar:$INTROOT/lib/laserclient.jar:$INTROOT/lib/laserconsole.jar:$INTROOT/lib/lasercore.jar:$INTROOT/lib/laserdefinition.jar:$INTROOT/lib/laserutil.jar:$INTROOT/lib/mail.jar:$ACSROOT/lib/log4j-1.2.8.jar:$CLASSPATH


# Finally run NetBeans
#/diskb/alma_tmp/Netbeans/bin/runide.sh -cp:a $CLASSPATH

# If the jar files are in the right place, I do not need anything else!
/diskb/alma_tmp/Netbeans/bin/runide.sh



#
# ___oOo___
