#! /bin/bash
OF=result.out
FILES=`ls ~/bulkDataNTGenSender*`

echo $FILES
rm -rf $OF

for f in $FILES
do	
	MACHINE=`echo $f | awk 'BEGIN {FS="."}; {print $2}'`
	OF=$MACHINE.out
	rm -rf $OF
	grep 'Transfer rate' $f | awk -v M=$MACHINE '{t=substr($1,12,13)*3600+substr($1,15,16)*60+substr($1,18); printf("%s, %.3f, %s\n", substr($1,12), t, $10)}' >> $OF
#	egrep 'proto|cache' $f	>> $OF
done
gnuplot -p plot