/*
 * generated by Xtext
 */
package alma.acs.tmcdb.grammardef;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TmcdbTablesRuntimeModule extends alma.acs.tmcdb.grammardef.AbstractTmcdbTablesRuntimeModule {

}
