#! /bin/sh
. acsstartupConstants
. acsstartupAcsInstance
. acsstartupLogging.sh

#*******************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) National Research Council of Canada, 2009 
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#
# "@(#) $Id: acsStartContainerWithCASA,v 1.4 2011/06/28 22:16:44 javarias Exp $"
#
# who        when       what
# --------   --------   ----------------------------------------------
# agrimstrup 2009-09-12 created
#

ACS_LOG_COMMAND $@

# Access to ACS-supplied modules may still be necessary so
# the PYTHONPATH has to include both the CASA and ACS
# site-package directories.  This is true for some shared
# libraries as well.  CASA is given priority in the
# ordering.
PYTHONPATH=`acsutilCASAPathInsert PYTHONPATH`
LD_LIBRARY_PATH=`acsutilCASAPathInsert LD_LIBRARY_PATH`
export LD_PRELOAD=$CASA_ROOT/lib/libgfortran.so.1
# Start the container in the CASA environment
acsStartContainer "$@"

#
# ___oOo___
