#! /bin/bash
. acsstartupAcsPorts
. acsstartupConstants
. acsstartupAcsInstance
. acsstartupLogging.sh
#*******************************************************************************
# E.S.O. - ACS project
#
# "@(#) $Id: acsStartJava,v 1.35 2006/05/09 15:19:42 acaproni Exp $"
#
# who       when      what
# --------  --------  ----------------------------------------------
# mschilli 2004-04-15 added proper command line parsing, added cmdline option -D for JAVA_OPTIONS
# mschilli 2003-11-03 export of some env.vars can now be suppressed with option '-noexport' (as arg #1)
# gchiozzi 2003-07-04 Set also Name Service reference
# gchiozzi 2003-05-27 Added setting .jacorb.properties in classpath inside $ACS_ABEANS_CONFIG
# david 2003-05-14 changed to bash for tat tests
# msekoran 2003-01-24 Added JAVA_ORB option
# gchiozzi 2002-10-14 Added passing more command line parameters to final java command line
# gchiozzi 2002-10-02 Added handling of -endorsed as first option.
# gchiozzi 2002-10-02 Fixed small bug in building endorsed lib path
# gchiozzi 2002-03-13 Added handling of JAVA_OPTIONS environment variable
# gchiozzi 2002-03-13 Added handling of endorsed directory.
# gchiozzi 2002-02-27 Changed shell from /din/sh to /bin/ksh
# jdovc     20/12/01  created
#

#************************************************************************
#   NAME        acsStartJava
#
#   SYNOPSIS
#
#   DESCRIPTION
#
#   FILES
#
#   ENVIRONMENT
#
#   RETURN VALUES
#
#   CAUTIONS
#
#   EXAMPLES
#
#   SEE ALSO
#
#   BUGS
#
#------------------------------------------------------------------------
#
#
# CLASSPATH separator -- set to ":" for UNIX, ";" for Windows

if [ "$OSYSTEM" = "cygwin" ]
then
    CPSEP=";"
else
    CPSEP=":"
fi

###
### ----------- Command Line Parsing ---------------------

# Fisrt dir of intlist
INSTALL_ROOT=`echo $INTLIST | awk -F: '{print $1}'`

#
# These will contain the parsing results (CL_XXX, CL = command line)
#
CL_ENDORSED=
CL_NOEXPORT=
CL_MANAGERREF=
CL_BASEPORT=
CL_JAVAPROPS=
CL_HELP=
CL_JARPATH=
CL_JARS=
CL_NAC=
CL_NCL=
CL_DEBUGPORT=
CL_NODIRECTORY=
CL_VMTOOLS=
CL_JVMOPTIONS=

#
# These options can be recognized (longopts comma-separated. colon means argument is required)
#
LONGOPTS=jvmOption:,help,endorsed,noexport,managerReference:,baseport:,jarpath:,addToClasspath:,noClassLoader,noAutoClasspath,debugport:,noDirectory,vmtools
SHORTOPTS=hm:b:D:j:v:

#
# Usage info. Be nice and keep this up-to-date!
#
function printUsage {
   echo "Starts a Java program"
   echo ""
	echo "Usage: `basename $0` [OPTIONS]  java_class  main_args"
	echo "Options: "
	echo "   -endorsed                                        try this on xml parser errors"
	echo "   -noexport                                        try this on environment variable errors"
	echo "   -m | -managerReference MGR                       the corbaloc of your favorite manager"
	echo "   -b | -baseport INSTANCE                          the acs instance (0-9) you want to use"
	echo "   -D PROP=VAL [-D PROP=VAL ...]                    system property definitions to pass to the JVM"
	echo "   -j | -jarpath someDir/lib[:someOtherDir/lib]     allows developer to set directories where jar files can be found"
	echo "   -addToClasspath someJar.jar[:someOtherJar.jar]   allows developer to pick special jar files to be added to the \$CLASSPATH"
	echo "   -noAutoClasspath                                 do not generate automatically the CLASSPATH adding all jar files in the jarpath. "
	echo "   -noClassLoader                                   do not use the special ACS class loader to find the jar files,"
	echo "                                                       all files must be found in the CLASSPATH."
	echo "   -debugport PORT                                  the port on which a remote debugger may access the JVM"
	echo "   -noDirectory                                     do not create an acs instance directory"
	echo "   -vmtools                                         start JVM Tools together with the application"
	echo "   -v | -jvmOption option [-jvmOption option]       an option for the JVM"
	echo "   -h | -help                                       prints this help and exits"
}

#
# Run getopt (posixly_correct needed). We run twice:
# First run is simply to check the commandline for correctness
# Second run is the real deal which replaces the command line args with getopt's output
export POSIXLY_CORRECT=1

getopt -n `basename $0` -u -a -l $LONGOPTS $SHORTOPTS "$@" || {
   printUsage
	exit $EC_BADARGS;
}

set -- `getopt -u -a -l $LONGOPTS $SHORTOPTS "$@"`

#
# Iterate over getopt's output and set CL_XXX variables accordingly
#
while : 
do
	case "$1" in
	--endorsed)         CL_ENDORSED=true ;;
	--noexport)         CL_NOEXPORT=true ;;
	--managerReference) CL_MANAGERREF=$2 ; shift ;;
	-m)                 CL_MANAGERREF=$2 ; shift ;;
	--baseport)         CL_BASEPORT=$2 ; shift ;;
	-b)                 CL_BASEPORT=$2 ; shift ;;
	-D)                 CL_JAVAPROPS=$CL_JAVAPROPS\ -D$2 ; shift ;;
	--jarpath)          CL_JARPATH=$2 ; shift ;;
	-j)                 CL_JARPATH=$2 ; shift ;;
	--addToClasspath)   CL_JARS=$2 ; shift ;;
	--noAutoClasspath)  CL_NAC=true ;;
	--noClassLoader)    CL_NCL=true ;;
	--debugport)        CL_DEBUGPORT=$2 ; shift ;;
	--noDirectory)      CL_NODIRECTORY=true ;;
	--vmtools)          CL_VMTOOLS=true ;;
	--help)             CL_HELP=true ;; 
	-h)                 CL_HELP=true ;; 
	-v)					CL_JVMOPTIONS=$CL_JVMOPTIONS\ $2 ; shift ;;
	--jvmOption)		CL_JVMOPTIONS=$CL_JVMOPTIONS\ $2 ; shift ;;
	--) break ;;
	esac
	shift
done
shift

#
# must be unset! otherwise our custom export() function
# that is defined below doesn't get used by the shell
#
export POSIXLY_CORRECT=
unset POSIXLY_CORRECT


if [ "$CL_HELP" ] ; then
   printUsage
   exit $EC_OK
fi

#
# (Note: Rest of command line now in $@ )
#
### ---------- End of Command Line Parsing -------------


#Set the port numbers...
ACS_MANAGER_PORT=`getManagerPort`
ACS_NAMING_SERVICE_PORT=`getNamingServicePort`
ACS_IR_PORT=`getIRPort`
export HOST=`getIP`


# set ACS_INSTANCE if it was specified on the command line
if [ "$CL_BASEPORT" ] ; then
	export ACS_INSTANCE=$CL_BASEPORT
fi

# set ACS_LOG_STDOUT if not defined
if [ "X$ACS_LOG_STDOUT" == "X" ]
then 
    export ACS_LOG_STDOUT="4"
fi


# append java system properties to JAVA_OPTIONS if such were specified on the command line
if [ "$CL_JAVAPROPS" ] ; then
	export JAVA_OPTIONS=$JAVA_OPTIONS\ $CL_JAVAPROPS
fi

# setup jar file search path that will be fed to 
# ACS class loader or to the acsGetSpecificJars seach script
if [ ! $CL_JARPATH ] ; then

    if [ -d ../lib ] ; then
	CL_JARPATH="../lib:"
    fi

    if [ -d $INTROOT ] && [ $INTROOT ] ; then
	CL_JARPATH="$CL_JARPATH$INTROOT/lib:"
    fi

    # Separation of dirs
    item_list=`echo $INTLIST | sed s/:/\ /g`
    for item in $item_list
    do
      if [ -d $item ] && [ $item ] ; then
	  CL_JARPATH="$CL_JARPATH$item/lib:"
      fi
    done

    if [ -d $ACSROOT ] && [ $ACSROOT ] ; then
	CL_JARPATH="$CL_JARPATH$ACSROOT/lib"
    fi
fi


###
### ------------- "-noexport" handling -------------------
### When launching AcsCommandCenter, it is fatal to export e.g. MANAGER_REFERENCE and others.
### Export of some variables can therefore be disabled through option "-noexport".

function export {

	if [ "$CL_NOEXPORT" ] ; then 
		## special treatment

		if [ "x${1:0:17}" == "xMANAGER_REFERENCE" \
		  -o "x${1:0:21}" == "xMANAGER_COMPUTER_NAME" \
		  -o "x${1:0:16}" == "xACS_NAME_SERVICE" \
		  -o "x${1:0:24}" == "xACS_INTERFACE_REPOSITORY" ]
		then
			ACS_LOG_DEBUG "(did NOT export $1 $2 $3 $4 $5 $6 $7 $8 $9)"
		else
			## default behavior
			builtin export $1 $2 $3 $4 $5 $6 $7 $8 $9
			ACS_LOG_DEBUG "exported $1 $2 $3 $4 $5 $6 $7 $8 $9"
		fi

	else
		## default behavior
		
		builtin export $1 $2 $3 $4 $5 $6 $7 $8 $9
		ACS_LOG_DEBUG "exported $1 $2 $3 $4 $5 $6 $7 $8 $9"
	fi
}
### ------------- End of "-noexport" handling --------------




ACS_LOG_INFO "Starting Java/abeans application: $@"
#
# Checks if the first parameter is -endorsed
# This force using the endorsed libraries, 
# that by default are not used
#
JAVA_ENDORSED=""
if [ "$CL_ENDORSED" ]; then
  #
  # Creates ENDORSED class path for Java
  #
  if [ -d $ACSROOT/lib/endorsed ]
  then
     JAVA_ENDORSED=$ACSROOT/lib/endorsed$CPSEP$JAVA_ENDORSED
  fi

  # Separation of dirs
  item_list=`echo $INTLIST | sed s/:/\ /g`
  JAVA_ENDORSED_TMP=""
  for item in $item_list
  do
     if [ -d $item/lib/endorsed ]
     then
        JAVA_ENDORSED_TMP=$JAVA_ENDORSED_TMP$item/lib/endorsed$CPSEP
     fi
  done
  JAVA_ENDORSED=$JAVA_ENDORSED_TMP$JAVA_ENDORSED

  if [ -d $INTROOT/lib/endorsed ]
  then
     JAVA_ENDORSED=$INTROOT/lib/endorsed$CPSEP$JAVA_ENDORSED
  fi
  if [ -d ../lib/endorsed ]
  then
     JAVA_ENDORSED=../lib/endorsed$CPSEP$JAVA_ENDORSED
  fi
  if [ "X$JAVA_ENDORSED" != X ]; then
     JAVA_ENDORSED="-Djava.endorsed.dirs=$JAVA_ENDORSED"
  fi
  ACS_LOG_INFO "Using endorsed jar files in: $JAVA_ENDORSED"
fi


#
# Xerces-J 2 property which prevents xerces from searching through all jar files for the file 'xerces.properties' 
# and finally using XIncludeParserConfiguration as the default configuration.
# XInclude is currently needed only by the CDB and the standard alternative without XInclude
# would be the XML11Configuration configuration.
# Unless we find problems we keep the XInclude as only configuration.
# If we find problem we can make this property configurable.
#
if [ "$CL_ENDORSED" ]; 
then
  #XERCES_CONFIG="-Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XML11Configuration"
  XERCES_CONFIG="-Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XIncludeParserConfiguration"
fi


#
# CORBA ORB specification
#
if [ "X$JAVA_ORB" == X ]; then
    # take JacORB as default
    JAVA_ORB="-Dorg.omg.CORBA.ORBClass=org.jacorb.orb.ORB -Dorg.omg.CORBA.ORBSingletonClass=org.jacorb.orb.ORBSingleton"
fi

#-------------------------------------------------------
# Handling of CLASSPATH.
# There are different options controlled controlled by
# the mutually exclusive options 
#  -noClassLoader and -addToClasspath
#

# If the -addToClasspath option is passed,
# the listed jar files are searched in $CL_JARS and added
# to the classpath so that they can be used to bootstrap 
# the system even before the classloader can take over
# (is requested).
#
if [ "X$CL_JARS" != "X" ]
then
    CLASSPATH=`acsGetSpecificJars $CPSEP $CL_JARS`$CLASSPATH
fi

#
# If we do not want to use the custom Java class loader,
# the command acsGetAllJars is used to retrieve all
# jar files in the $CL_JARPATH.
# The Java class loader cannot be usedwhen using some Java class
# that itself installs a class loader.
# An example of this is JUnit
#
if [ "X$CL_NCL" = "Xtrue" -a "X$CL_NAC" = "X" ]
then
    #
    # Retrieves all jar files for the CLASSPATH
    #
    CLASSPATH=`acsGetAllJars $CPSEP $CL_JARPATH`$CLASSPATH
#
# By default the custom Java class loader is used.
# In this case we need to have jACSUtil.jar in the CLASSPATH
#
elif [ "X$CL_NCL" = "X" ]
then
   # 
   # Sets the class loader and adds ACSUtil.jar to the CLASSPATH
   # 
   JAVA_OPTIONS=$JAVA_OPTIONS\ -Djava.system.class.loader=alma.acs.classloading.AcsSystemClassLoader\ -Dacs.system.classpath.jardirs=$CL_JARPATH

   JACSUTIL_JAR=`acsGetSpecificJars $CPSEP jACSUtil.jar`
   if [ "X$JACSUTIL_JAR" = "X" ]
   then    
       ACS_LOG_ERROR "Expected to find jACSUtil.jar in the ALMA Software directory structure but did not!"
       exit $EC_FAILURE
   fi
   
   CLASSPATH=$JACSUTIL_JAR$CLASSPATH
fi

#
# AcsLogManager should be used instead of JDK's LogManager to allow logging during Ctrl-C shutdown
#
JAVA_OPTIONS=$JAVA_OPTIONS\ -Djava.util.logging.manager=alma.acs.logging.AcsLogManager


#
# Creates default values for configuration files directory
# if not already given as environment variables.
#
if [ "X$ACS_ABEANS_CONFIG" = X ]
then
    export ACS_ABEANS_CONFIG=$ACSDATA/config/abeans/Config
fi

ACS_LOG_DEBUG "ACS abeans configuration directory: $ACS_ABEANS_CONFIG"

#
# Then add it to the CLASSPATH together with .jacorb.properties
# that we have put as well in the $ACS_ABEANS_CONFIG directory
#
CLASSPATH=$CLASSPATH$CPSEP$ACS_ABEANS_CONFIG$CPSEP$ACSDATA/config
export CLASSPATH
### ------------- End of CLASSPATH handling --------------


#
# Creates default values for Manager and Interface Repository,
# if not already given as environment variables.
#
if [ "$CL_MANAGERREF" ]; then
   export MANAGER_REFERENCE=$CL_MANAGERREF
   ACS_LOG_DEBUG "Command-line Manager Reference: $CL_MANAGERREF"
fi

if [ "X$MANAGER_REFERENCE" = X ]; then  
   export MANAGER_REFERENCE=corbaloc::$HOST:$ACS_MANAGER_PORT/Manager
fi

ACS_LOG_DEBUG "ACS Manager: $MANAGER_REFERENCE"

export MANAGER_COMPUTER_NAME=`echo $MANAGER_REFERENCE |  awk -F: '{print $3}'`

# If $ACS_NAME_SERVICE is not set, take the computer
# where Manager is located

if [ "X$ACS_NAME_SERVICE" = X ]; then
   export ACS_NAME_SERVICE=corbaloc::$MANAGER_COMPUTER_NAME:$ACS_NAMING_SERVICE_PORT/NameService
fi

ACS_LOG_DEBUG "ACS Name Service: $ACS_NAME_SERVICE"

#If $ACS_INTERFACE_REPOSITORY is not set, take the computer, where Manager
#is located

if [ "X$ACS_INTERFACE_REPOSITORY" = X ]; then
   export ACS_INTERFACE_REPOSITORY=corbaloc::$MANAGER_COMPUTER_NAME:$ACS_IR_PORT/InterfaceRepository
fi

ACS_LOG_DEBUG "ACS Interface Repository: $ACS_INTERFACE_REPOSITORY"

#
# Creates default values tmp directory
# if not already given as environment variables.
#
if [ ! $CL_NODIRECTORY ] ; then
   if [ "X$ACS_TMP" = X ]; then  
      export ACS_TMP=`getInstanceDirName $ACS_INSTANCE`

      #
      # Makes sure that the directory for temporary 
      # ACS_INSTANCE files exists.
      # If the directory is created locally, removes it at the end.
      #
      if [ ! -d `getInstanceDirName $ACS_INSTANCE` ]
        then
	  if ! createInstanceDirectory $ACS_INSTANCE
          then 
	      ACS_LOG_ERROR "For some reason this script could not create `getInstanceDirName $ACS_INSTANCE`!"
	      ACS_LOG_ERROR "    Check $ACS_INSTANCES_DIR for free base ports!"
	      exit $EC_CANNOTCREATE
	  fi
      fi
   fi
fi

###
### -------------  "remoteDebug" handling  ---------------
###
if [ "$CL_DEBUGPORT" ] ; then
	JAVA_OPTIONS="$JAVA_OPTIONS -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=$CL_DEBUGPORT -Djava.compiler=NONE"

   ACS_LOG_INFO "The JVM will accept a remote debugger on port $CL_DEBUGPORT"
fi
### ---------- End of "remoteDebug" handling -------------



###
### ------------- "vmtools" handling -------------------
###
LAUNCHER=
if [ "$CL_VMTOOLS" ] ; then
   LAUNCHER=alma.acs.vmtools.Launcher
fi
### ---------- End of "vmtools" handling -------------

###
### ------------- "JVM options" handling -----------------
###
if [ "$CL_JVMOPTIONS" ] ; then
	JAVA_PUREFLAGS="$JAVA_PUREFLAGS $CL_JVMOPTIONS"
fi
### ---------- End of "JVM options" handling -------------


ACS_LOG_DEBUG "Running the following command:"
    
if [ "X$MAKE_PURE" = "Xon" ]; then
   JAVA_PUREFLAGS="-Xint -Xrunpagent:-OUT=["mempro.jpt"]"
fi

JAVA_COMMAND_LINE="java $JAVA_PUREFLAGS -classpath $CLASSPATH $JAVA_ENDORSED $XERCES_CONFIG $JAVA_ORB -Duser.timezone=UTC -Dabeans.home=$ACS_ABEANS_CONFIG -DACS.manager=$MANAGER_REFERENCE -DORBInitRef.NameService=$ACS_NAME_SERVICE  -DACS.repository=$ACS_INTERFACE_REPOSITORY -DACS.tmp=$ACS_TMP -DACS.baseport=$ACS_INSTANCE -DACS.data=$ACSDATA -DACS.logstdout=$ACS_LOG_STDOUT $JAVA_OPTIONS $LAUNCHER $@"

ACS_LOG_DEBUG "$JAVA_COMMAND_LINE"

#
# .... and finally executes the Java command line
#      storing the JVM return code
#

$JAVA_COMMAND_LINE
JVM_RETURN_CODE=$?

exit $JVM_RETURN_CODE

# __oOo__
