#! /bin/bash
. acsstartupAcsPorts
. acsstartupLogging.sh
. acsstartupConstants
. acsstartupAcsInstance
#*******************************************************************************
# E.S.O. - VLT project
#
# "@(#) $Id: acsStop,v 1.13 2006/01/09 22:18:51 dfugate Exp $"
#
# who       when      what
# --------  --------  ----------------------------------------------
# mschilli 2004-04-16 added proper command line parsing
# david 2003-05-14 changed to bash for tat tests
# gchiozzi 2002-12-12 acsLogSvc was missing for SunOS
# gchiozzi 2002-11-22 Added stopping CDB
# gchiozzi 2002-09-30 Removed CDB Server. Not needed any more.
# bjeram 2002-04-10 added kill acslogsvc
# psivera  2002-03-18 ported to SUN Solaris
# gchiozzi 2001-09-19 created
#

#************************************************************************
#   NAME
# 
#   SYNOPSIS
# 
#   DESCRIPTION
#
#   FILES
#
#   ENVIRONMENT
#
#   RETURN VALUES
#
#   CAUTIONS
#
#   EXAMPLES
#
#   SEE ALSO
#
#   BUGS     
#
#------------------------------------------------------------------------
#

###
### ----------- Command Line Parsing ---------------------

#
# These will contain the parsing results (CL_XXX, CL = command line)
#
CL_BASEPORT=
CL_HELP=

#
# These options can be recognized (longopts comma-separated. colon means argument is required)
#
LONGOPTS=help,baseport:
SHORTOPTS=hb:

#
# Usage info. Be nice and keep this up-to-date!
#
function printUsage {
   echo "Stops an Acs instance"
   echo ""
	echo "Usage: `basename $0` [OPTIONS]  "
	echo "Options: "
	echo "   -b | -baseport INSTANCE        the acs instance (0-9) you want to use"
   echo "   -h | -help                     prints this help and exits"
}

#
# Run getopt (posixly_correct needed). We run twice:
# First run is simply to check the commandline for correctness
# Second run is the real deal which replaces the command line args with getopt's output
export POSIXLY_CORRECT=1

getopt -n `basename $0` -Q -u -a -l $LONGOPTS $SHORTOPTS "$@" || {
   printUsage
	exit $EC_BADARGS;
}

set -- `getopt -u -a -l $LONGOPTS $SHORTOPTS "$@"`

#
# Iterate over getopt's output and set CL_XXX variables accordingly
#
while : 
do
	case "$1" in
	--baseport)         CL_BASEPORT=$2 ; shift ;;
	-b)                 CL_BASEPORT=$2 ; shift ;;
	--help)             CL_HELP=true ;; 
	-h)                 CL_HELP=true ;; 
	--) break ;;
	esac
	shift
done
shift

# restore 
export POSIXLY_CORRECT=
unset POSIXLY_CORRECT

if [ "$CL_HELP" ] ; then
   printUsage
   exit $EC_OK
fi

#
# (Note: Rest of command line now in $@ )
#
### ---------- End of Command Line Parsing -------------


export HOST=`getIP`

#Check command-line args for baseport option
if [ "$CL_BASEPORT" ]
then
    export ACS_INSTANCE=$CL_BASEPORT
fi

########################################################################
#SANITY CHECKS----------------------------------------------------------
#If it's undefined, the developer must have meant the default
if [ "X$ACS_INSTANCE" == "X" ]
then 
    export ACS_INSTANCE="0"
fi

#Cannot shutdown everything if we don't know the process IDs.
if [ ! -d `getInstanceDirName $ACS_INSTANCE` ]
then
    ACS_LOG_ERROR "Unable to shutdown because the lock directory '$ACSDATA/tmp/ACS_INSTANCE.$ACS_INSTANCE' does not exist!"
    ACS_LOG_INFO "An alternative is to use the 'killACS' command which kills all ACS processes '$USER' owns"
    exit $EC_CANNOTUSE
fi

#Cannot shutdown everything if this user does not own the processes.
if [ ! -w `getInstanceDirName $ACS_INSTANCE` ]
then
    ACS_LOG_ERROR "Unable to shutdown because the lock directory '`getInstanceDirName $ACS_INSTANCE`' is not owned by '$USER'!"
    exit $EC_CANNOTUSE
fi

#Lock file specifically for the acsStop script
if [ -e `getInstanceDirName $ACS_INSTANCE`/.stoplock ]
then
    ACS_LOG_ERROR "Unable to shutdown because another process is attempting to stop the '$ACS_INSTANCE' instance of ACS!"
    ACS_LOG_ERROR "    Please be patient (or try removing `getInstanceDirName $ACS_INSTANCE`/.stoplock)."
    exit $EC_CANNOTUSE
else
    touch `getInstanceDirName $ACS_INSTANCE`/.stoplock
fi

ACS_LOG_INFO "Stopping all ACS processes using 'ACS_INSTANCE=$ACS_INSTANCE'"

#go to the directory where all process IDs are stored
cd `getInstanceDirName $ACS_INSTANCE`

########################################################################
#SHUTDOWN CONTAINERS----------------------------------------------------
ACS_LOG_INFO "Shutting down containers..."

file=`cat USED_CONTAINER_PORTS | cut -d' ' -f1`

for line in $file
do
  ACS_LOG_INFO "Shutting down $line container"
  acsStopContainer $line &> /dev/null
done

########################################################################
#SHUTDOWN MANAGER-------------------------------------------------------
ACS_LOG_INFO "Stopping Manager"
ACS_MANAGER_PORT=`getManagerPort`
acsStopManager -m corbaloc::$HOST:$ACS_MANAGER_PORT/Manager

########################################################################
#SHUTDOWN ORB SERVICES--------------------------------------------------
acsStopORBSRVC

# ___oOo___
