#!/bin/bash
OLD_CDB=$ACS_CDB
ACS_CDB=../test

#Start the ORB services and manager.
acsutilTATPrologue

echo " Starting Test Java Container"
acsutilAwaitContainerStart -java frodoContainer
echo " Starting Test C++ Container"
acsutilAwaitContainerStart -cpp bilboContainer
