#! /bin/bash
#*******************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) European Southern Observatory, 2002
# Copyright by ESO (in the framework of the ALMA collaboration),
# All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA 02111-1307  USA
rm -rf doc2
mkdir -p doc2


XSDDOC_JAR="../lib/xsddoc.jar"
if [ ! -e $XSDDOC_JAR ] 
then
   XSDDOC_JAR_DIR=`searchFile lib/xsddoc.jar`
   XSDDOC_JAR=$XSDDOC_JAR_DIR/lib/xsddoc.jar
fi

echo "=== Processing"
export CLASSPATH=$XSDDOC_JAR:$ACSROOT/lib/xalan.jar:$ACSROOT/lib/xalan_serializer.jar:$CLASSPATH
ant 
echo "=== Generated documentation listing"
ls -R doc2
