#ifndef _TASKCOMPONENT_IDL_
#define _TASKCOMPONENT_IDL_

/*******************************************************************************
*    ALMA - Atacama Large Millimiter Array
*
*    (c) European Southern Observatory, 2002
*    Copyright by ESO (in the framework of the ALMA collaboration)
*    and Cosylab 2002, All rights reserved
*
*    This library is free software; you can redistribute it and/or
*    modify it under the terms of the GNU Lesser General Public
*    License as published by the Free Software Foundation; either
*    version 2.1 of the License, or (at your option) any later version.
*
*    This library is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*    Lesser General Public License for more details.
*
*    You should have received a copy of the GNU Lesser General Public
*    License along with this library; if not, write to the Free Software
*    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
*
* "@(#) $Id: taskComponent.idl,v 1.1 2005/07/29 21:43:58 sharring Exp $"
*
* who       when      what
* --------  --------  ----------------------------------------------
* bjeram    2004-09-22  created
*/

#include <acscomponent.idl>
#include "taskErrType.idl"

#pragma prefix "alma"

module ACS
{

	typedef sequence<string> StringSequence;

    /** @interface TaskComponent
     * This is a generic interface for TaskComponent, which contains run operation.
     * The TaskComponent is an ACS component.
     */
    interface TaskComponent : ACS::ACSComponent
	{
	
	/**
	 * TaskComponent's run method
	 * @param: param parameter to the run method of the TaskComponent
	 * @fileName: fileName the filename for the task's metadata (parameter set definition) xml file,
	 *            which contains information about the parameters for a task (e.g. names, types, defaults, help, etc)
	 */
	void run(in StringSequence commandLineArgs, in string fileName) raises (taskErrType::TaskRunFailureEx);
	};//interface TaskComponent

};//module ACS


#endif
