.TH "ACSLog::RTContext" 3 "19 Sep 2001" "ACSLogService" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACSLog::RTContext \- 
.SH SYNOPSIS
.br
.PP
\fC#include <acslog.idl>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBthread\fP"
.br
.ti -1c
.RI "string \fBprocess\fP"
.br
.ti -1c
.RI "string \fBhost\fP"
.br
.ti -1c
.RI "string \fBaddContext\fP"
.br
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
structure to represent Run-Time Context information 
.PP
.SH "MEMBER DATA DOCUMENTATION"
.PP 
.SS "string ACSLog::RTContext::thread"
.PP
Thread ID or name. 
.SS "string ACSLog::RTContext::process"
.PP
Process ID (=PID) or process name. 
.SS "string ACSLog::RTContext::host"
.PP
Host name or its IP address. 
.SS "string ACSLog::RTContext::addContext"
.PP
Additional context information. 

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for ACSLogService from the source code.