.TH "ACSLog::SourceInfo" 3 "19 Sep 2001" "ACSLogService" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACSLog::SourceInfo \- 
.SH SYNOPSIS
.br
.PP
\fC#include <acslog.idl>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBfile\fP"
.br
.ti -1c
.RI "string \fBroutine\fP"
.br
.ti -1c
.RI "unsigned long \fBline\fP"
.br
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
structure to represent Source information 
.PP
.SH "MEMBER DATA DOCUMENTATION"
.PP 
.SS "string ACSLog::SourceInfo::file"
.PP
file name. 
.SS "string ACSLog::SourceInfo::routine"
.PP
routine name. 
.SS "unsigned long ACSLog::SourceInfo::line"
.PP
line number. 

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for ACSLogService from the source code.