.TH "acslog.idl" 3 "19 Sep 2001" "ACSLogService" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acslog.idl \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'acserr.idl'\fP
.br
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBACSLog\fP"
.br
.in -1c
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for ACSLogService from the source code.