#! /bin/bash
#*******************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) European Southern Observatory, 2002
# Copyright by ESO (in the framework of the ALMA collaboration),
# All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA 02111-1307  USA
#
# "@(#) $Id: jcontTATEpilogueRestart,v 1.1 2008/07/07 08:56:38 cparedes Exp $"
#
# who       when      what
# hsommer 2004-09-17 copied from jcontexmpl
# rtobar  2008-02-26 added classpath extension for JMX test


acsutilTATEpilogue 

mv $ACSDATA/config/orb.properties.bk $ACSDATA/config/orb.properties

jcontTATPrologue

