#!/bin/bash
# -*- ksh -*-
# $Id: eventGUI,v 1.6 2011/11/30 22:54:32 jschwarz Exp $
#
# DESCRIPTION
#    Starts the ACS Event Browser
#
#
# OPTIONS
#    No options
#
#
# AUTHOR
#    Joseph Schwarz, 30 June 2010

. acsstartupAcsPorts
. acsstartupConstants
. acsstartupAcsInstance

#Set the port numbers...
ACS_MANAGER_PORT=`getManagerPort`
export HOST=`getIP`

if [ X"$MANAGER_REFERENCE" = X ]; then  
   export MANAGER_REFERENCE=corbaloc::$HOST:$ACS_MANAGER_PORT/Manager
fi

ACS_LOG_DEBUG "acsStartJava" "ACS Manager: $MANAGER_REFERENCE"

dir=$(searchFile bin/eventGUI)

$dir/lib/ACS_eventGUI/eventGUI \
     -consoleLog \
     -vmargs \
     -DACS.manager=$MANAGER_REFERENCE \
     -DACS.tmp=$ACS_TMP \
     -Djacorb.log.initializer=alma.acs.logging.adapters.AcsJacorbLoggingInitializer \
     -DACS.log.minlevel.namedloggers="jacorb@eventGUI=5,5:scxml@eventGUI=5,5" \
     -Dorg.apache.commons.logging.LogFactory=alma.acs.logging.adapters.CommonsLoggingFactory \
     $JAVA_OPTIONS

