#! /bin/sh
#*******************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) European Southern Observatory, 2007 
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#
# "@(#) $Id: testACS_LOG_STDOUT,v 1.1 2007/01/02 16:12:07 bjeram Exp $"
#
# who       when      what
# --------  --------  ----------------------------------------------
# bjeram  2007-01-02  created
#
echo "Test w/o ACS_LOG_STDOUT"
unset ACS_LOG_STDOUT
testMacros

echo "Test with ACS_LOG_STDOUT=5"
export ACS_LOG_STDOUT=5
testMacros

echo "Test with ACS_LOG_STDOUT=4"
export ACS_LOG_STDOUT=4
testMacros

#
# ___oOo___
