#! /bin/bash
#*******************************************************************************

echo " ****************** MonitorArchiverTATPrologue ************* "
ACS_CDB=$PWD

echo " Starting ORB Services and Manager"
acsutilTATPrologue -l --noloadifr
acsutilTATTestRunner acsStartContainer -java ARCHIVE/TMCDB/MONITOR_CONTROL/javaContainer &> container.out &
