#! /bin/bash
. acsstartupLogging.sh
#*******************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) European Southern Observatory, 2002
# Copyright by ESO (in the framework of the ALMA collaboration)
# and Cosylab 2002, All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA 02111-1307  USA
#
# "@(#) $Id: cdbjDALClearCache,v 1.6 2006/06/22 06:25:41 cparedes Exp $"
#
# who       when      what
# --------  --------  ----------------------------------------------
# cparedes 2006-06-20 using DAL_REFERENCE when the -k option is not used
# dvitas 2003-04-14 changed package name and removed unused argument
# bjeram 2002-11-22 removed -OAport
# bjeram 2002-10-24 created
#

arg1=$1;
arg2=$2;
arg3=$3;

if [ "$arg2" != "-k" ] && [ "$arg1" != "-k" ]
then
#use the DAL_REFERENCE
    if [ "X$DAL_REFERENCE" != "X" ] 
    then
	arg2="-k";
	arg3=$DAL_REFERENCE;
    fi
fi

acsStartJava com.cosylab.cdb.jdal.ClearCache $arg1 $arg2 $arg3

