#! /bin/sh
#*******************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) European Southern Observatory, 2000
# Copyright by ESO (in the framework of the ALMA collaboration)
# and Cosylab 2002, All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA 02111-1307  USA
#
# "@(#) $Id: alarmService,v 1.2 2009/12/20 17:13:20 acaproni Exp $"

# Set logger levels to INFO unless the env vars are set already.
# This is to avoid especially the verbose jacorb logging we would get from the currently low schema default log levels of 2
if [ "X$ACS_LOG_STDOUT" = "X" ]; then
    export ACS_LOG_STDOUT=4
fi
if [ "X$ACS_LOG_CENTRAL" = "X" ]; then
    export ACS_LOG_CENTRAL=4
fi
acsStartJava -endorsed alma.acs.alarmsystem.corbaservice.AlarmSystemCorbaServer -jacorb $*
