#ifndef _ERROR_COMPONENT_H
#define _ERROR_COMPONENT_H
/*******************************************************************************
*    ALMA - Atacama Large Millimiter Array
*    (c) Associated Universities Inc., 2002 
*    (c) European Southern Observatory, 2002
*    Copyright by ESO (in the framework of the ALMA collaboration)
*    and Cosylab 2002, All rights reserved
*
*    This library is free software; you can redistribute it and/or
*    modify it under the terms of the GNU Lesser General Public
*    License as published by the Free Software Foundation; either
*    version 2.1 of the License, or (at your option) any later version.
*
*    This library is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*    Lesser General Public License for more details.
*
*    You should have received a copy of the GNU Lesser General Public
*    License along with this library; if not, write to the Free Software
*    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
*
* "@(#) $Id: acsexmplErrorComponentImpl.h,v 1.1 2006/04/12 16:35:05 gchiozzi Exp $"
*
* who       when      what
* --------  --------  ----------------------------------------------
* david 2002-09-26 added more comments
* david  25/09/02  created
*/

#ifndef __cplusplus
#error This is a C++ include file and cannot be used from plain C
#endif

///This example is unique because it is derived from CharacteristicComponent's
///superclass, ACSComponent.
#include <acscomponentImpl.h>

///This is the CORBA stub client header for ACSErrTypeCommon.idl where the 
///definition of the CORBA exception is found.
#include <ACSErrTypeCommon.h>

/**
 *  The empty CORBA servant interface, POA_acsexmplErrorComponent::ErrorComponent,
 *  is obtained from this header file and is automatically generated from 
 *  ErrorComponent's Interface Definition File (i.e., acsexmplErrorComponent.idl) 
 *  by CORBA.
 */
#include <acsexmplErrorComponentS.h>
 
using namespace acscomponent;

/** @file acsexmplErrorComponentImpl.h
 */

/** @defgroup ACSEXMPLHWDOC Hello World
 *  @{
 * @htmlonly
<hr size="2" width="100%">
<div align="left">
<h2>Description</h2>
Hello World is the simplest component within the acsexmpl module. It provides 
two methods, displayMessage() which prints "Hello World" to standard out and
badMethod which raises a CORBA exception.
<br>
<br>
<h2>What can I gain from this example?</h2>
<ul>
  <li>an example derived from the ACS::ACSComponent IDL interface.</li>
  <li>an introduction to the ACS API.</li>
  <li>limited ACS logging macros.</li>
  <li>raising CORBA exceptions.</li>
</ul>
<br>
<br>
<h2>Links</h2>
<ul>
  <li><a href="classErrorComponent.html">Hello World Class Reference</a></li>
  <li><a href="interfaceacsexmplErrorComponent_1_1ErrorComponent.html">Hello World IDL Documentation</a></li>
</ul>
</div>
   @endhtmlonly
 * @}
 */

/**
 * This class shows how to make a Hello World component.
 * It provides one synchronous method: displayMessage() which just prints
 * "Hello World" to the command-line where the container that activated
 * an instance of this component was started from. badMethod() is a trivial
 * method showing developers how to raise ACS (i.e., CORBA) exceptions.
 *
 * All components should inherit from CharacteristicComponentImpl or it's 
 * superclass, ACSComponentImpl, to remain  compatiable with ACS tools such 
 * as objexp (i.e., a GUI used to manipulate components).  This class also 
 * derives from POA_acsexmplErrorComponent::ErrorComponent which is a class automatically 
 * generated by CORBA from ErrorComponent's IDL file.
 * @version "@(#) $Id: acsexmplErrorComponentImpl.h,v 1.1 2006/04/12 16:35:05 gchiozzi Exp $"
 */
class ErrorComponent: public virtual ACSComponentImpl,     //Component superclass
		  public POA_acsexmplErrorComponent::ErrorComponent    //CORBA servant stub
{    
  public:
    /**
     * Constructor
     * @param poa Poa which will activate this and also all other components. Developers need
     * not be concerned with what a PortableServer does...just pass it to the superclass's
     * constructor.
     * @param name component's name. All components have a name associated with them so other 
     * components and clients can access them.
     */
    ErrorComponent(
	       const ACE_CString& name,
	       maci::ContainerServices * containerServices);
    
    /**
     * Destructor
     */
    virtual ~ErrorComponent();
    
    /* --------------------- [ CORBA interface ] ----------------------*/    
    /**
     * Displays "Hello World" to the console.
     * Implementation of IDL displayMessage().
     * @htmlonly
       <br><hr>
       @endhtmlonly
     */     
    virtual void 
    displayMessage ()
	throw (CORBA::SystemException);

    /**
     * Simple method raises a remote exception within the calling client.
     * Implementation of IDL badMethod().
     * @param depth depth of the error trace
     * @htmlonly
       <br><hr>
       @endhtmlonly
     */     
    virtual void
    badMethod(CORBA::Short depth) 
	throw (CORBA::SystemException, ACSErrTypeCommon::GenericErrorEx);


    /** 
     *  Simple method that returns an ACSErr::Completion.
     *  @param depth depth of the error trace, if <=0, returns OK completion
     *  @return ACSErr::Completion
     *  @htmlonly
     *  <br><hr>
     *  @endhtmlonly
     */
    virtual ACSErr::Completion *returnCompletion(CORBA::Short depth) 
	throw (CORBA::SystemException);

  private:
    /**
     * This method simply throw an exception containing
     * an error trace with the requested depth, if > 0
     * Otherwise just returns.
     *
     * Notice that this method throws a LOCAL exception xxxExImpl 
     * and not a remote exception xxx
     *
     * @param depth depth of the error trace
     */     
    virtual void
    errorTrace(CORBA::Short depth) 
	throw (ACSErrTypeCommon::GenericErrorExImpl);

};

#endif /*!_ERROR_COMPONENT_H*/



