/*
 *    ALMA - Atacama Large Millimiter Array
 *    (c) European Southern Observatory, 2002
 *    Copyright by ESO (in the framework of the ALMA collaboration)
 *    and Cosylab 2002, All rights reserved
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 2.1 of the License, or (at your option) any later version.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
 *    MA 02111-1307  USA
 */
package alma.acs.gui.loglevel.tree;

import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;

import alma.acs.gui.loglevel.leveldlg.LogLevelDlg;
import alma.acs.gui.loglevel.tree.node.TreeContainerInfo;


import si.ijs.maci.Container;
import si.ijs.maci.ContainerInfo;
import si.ijs.maci.LoggingConfigurable;
import si.ijs.maci.LoggingConfigurableHelper;
import si.ijs.maci.Manager;

/**
 * The class to receive mouse events generated by the tree
 * 
 * @author acaproni
 *
 */
public class TreeMouseListener extends MouseAdapter {
	
	// The tree generating events
	private LogLvlTree tree;
	
	// The node of the containers
	private DefaultMutableTreeNode containersNode;
	
	// The model of the tree
	private LogLvlTreeModel model;
	
	// The popup menu
	private TreePopupMenu popupMenu;
	
	/**
	 * Constructor 
	 * 
	 * @param logLevelTree The tree generating events
	 */
	public TreeMouseListener(LogLvlTree logLevelTree) {
		if (logLevelTree==null) {
			throw new IllegalArgumentException("Invalid null LogLvlTree in constructor");
		}
		tree=logLevelTree;
		model = (LogLvlTreeModel)tree.getModel();
		popupMenu= new TreePopupMenu(model);
		containersNode = model.findNode(null, "Containers", 0);
		if (containersNode==null) {
			throw new IllegalStateException("Containers node not found in the tree");
		}
	}
	
	/**
	 * @see java.awt.event.MouseListener
	 */
	public void mousePressed(MouseEvent e) {
		TreePath selPath = tree.getPathForLocation(e.getX(), e.getY());
		if (selPath == null) {
			// No object selected but the user expand/compress a node
			return;
		}
		
		if (e.getClickCount()==2) {
			tree.setSelectionPath(selPath);
			showLoggingConfigDlg(selPath);
			return;
		}
		if (e.isPopupTrigger()) {
			Toolkit tk = Toolkit.getDefaultToolkit();
			PointerInfo pi = MouseInfo.getPointerInfo();
			Point mouseLocation = pi.getLocation();
			SwingUtilities.convertPointFromScreen(mouseLocation, tree);
			popupMenu.show(tree,mouseLocation.x,mouseLocation.y);
		}
		
	}
	
	/**
	 * Show the dialog to read and configure the log level
	 * 
	 * @param path The path of the selected node
	 *
	 */
	private void showLoggingConfigDlg(TreePath path) {
		if (path==null) {
			throw new IllegalArgumentException("Invalid null path");
		}
		DefaultMutableTreeNode selNode = (DefaultMutableTreeNode)path.getLastPathComponent();
		boolean implementsLogging=implementsLoggingConfigurable(selNode);
		System.out.println("Object selected: "+ selNode.toString());
		System.out.println("Implements interface "+implementsLogging);
		if (!implementsLogging) {
			return;
		}
		// Get a reference to the LoggingConfigurable for the 
		// selected item
		LoggingConfigurable logConf = null;
		if (selNode.isRoot()) {
			try {
				logConf= getLogConfFromManager();
			} catch (Throwable t) {
				JOptionPane.showInternalMessageDialog(tree, "Error getting the LoggingConfigurable:\n"+t.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
				return;
			}
		} else {
			ContainerInfo cInfo;
			try {
				cInfo = ((TreeContainerInfo)selNode.getUserObject()).getClientInfo();
			} catch (Throwable t) {
				JOptionPane.showInternalMessageDialog(tree, "Error retrieving ContainerInfo from the node","Error", JOptionPane.ERROR_MESSAGE);
				return;
			}
			try {
				logConf=getLogConfFromContainer(cInfo);
			} catch (Throwable t) {
				JOptionPane.showInternalMessageDialog(tree, "Error getting the LoggingConfigurable:\n"+t.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
				return;
			}
		}
		if (logConf==null) {
			JOptionPane.showInternalMessageDialog(tree, "LoggingConfigurable is null", "Error", JOptionPane.ERROR_MESSAGE);
			return;
		}
		LogLevelDlg dlg = new LogLevelDlg(tree,logConf,selNode.getUserObject().toString());
		dlg.setVisible(true);
	}
	
	/**
	 * Get the LoggingConfigurable out of the manager
	 * 
	 * @return The LoggingConfigurable for the manager
	 */
	private LoggingConfigurable getLogConfFromManager() throws Exception {
		System.out.println("Getting LoggingConfigurable out of Manager");
		// Manager
		Manager mgr = model.getManagerRef();
		if (mgr==null) {
			throw new Exception("Invalid manager reference");
		}
		LoggingConfigurable logConf;
		try {
			logConf= LoggingConfigurableHelper.narrow(mgr);
		} catch (Throwable t) {
			throw new Exception("Error getting the LoggingConfigurable out of Manager:\n"+t.getMessage(),t);
		}
		return logConf;
	}
	
	/**
	 * Get the LoggingConfigurable out of the container
	 * 
	 * @return The LoggingConfigurable for the container
	 */
	private LoggingConfigurable getLogConfFromContainer(ContainerInfo info) throws Exception {
		if (info==null) {
			throw new IllegalArgumentException("Invalid null ContainerInfo");
		}
		LoggingConfigurable logConf;
		Container cnt = info.reference;
		if (cnt==null) {
			throw new Exception("The reference to the container is null in ContainerInfo");
		}
		try {
			logConf= LoggingConfigurableHelper.narrow(cnt);
		} catch (Throwable t) {
			throw new Exception("Error getting the LoggingConfigurable out of Container:\n"+t.getMessage(),t);
		}
		return logConf;
	}
	
	/**
	 * Check if the object represented by the node implements
	 * the LoggingConfigurable IDL interface.
	 * Actually the only ACS items implementing such an interface are
	 *   - the manager
	 *   - the containers
	 *   
	 * @param node The node to query
	 * @return true if the object implements LoggingConfigurable
	 */
	private boolean implementsLoggingConfigurable(DefaultMutableTreeNode node) {
		if (node==null) {
			throw new IllegalArgumentException("Invalid null node to query");
		}
		if (node.isRoot()) {
			// The root is the manager
			return true;
		}
		return containersNode.isNodeChild(node);
	}
}
