#! /bin/bash
. acsstartupAcsPorts
. acsstartupLogging.sh
. acsstartupConstants
. acsstartupAcsInstance
#*******************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) Associated Universities Inc., 2002 
# (c) European Southern Observatory, 2002
# Copyright by ESO (in the framework of the ALMA collaboration)
# and Cosylab 2002, All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA 02111-1307  USA
#
# "@@(#) $Id: maciManagerJ,v 1.53 2009/11/10 05:28:44 hyatagai Exp $"
#
# who       when      what
# -------- ---------- ----------------------------------------------
# msekoran 2003-05-09 Created.
#

#************************************************************************
#   NAME	maciManagerJ
#
#   SYNOPSIS
#
#   DESCRIPTION
#
#   FILES
#
#   ENVIRONMENT
#
#   RETURN VALUES
#
#   CAUTIONS
#
#   EXAMPLES
#
#   SEE ALSO
#
#   BUGS
#
#------------------------------------------------------------------------
#
#

INSTANCE_DIR=`getInstanceDirName $ACS_INSTANCE`
MANAGER_PIDFILE=$INSTANCE_DIR/$ACS_MANAGER_PIDFILE

#
# Save the process ID
#
ACS_MANAGER_PID=$$
if [ ! -d $INSTANCE_DIR ]
then
    ACS_LOG_ERROR "Unable to save manager's PID because '$INSTANCE_DIR' does not exist!"

elif [ ! -w $INSTANCE_DIR ]
then
    ACS_LOG_ERROR "Unable to save manager's PID because '$INSTANCE_DIR' is not owned by '$USER'!"

else
    #save the PID of this script so we can kill it later if we have to
    echo $ACS_MANAGER_PID  > $MANAGER_PIDFILE
fi


# ----------------------------------------------------------------

ACS_LOG_INFO "Starting jManager"

#
# Fetches the IP adress
#
export HOST=`getIP`

#
# If $NAMESERVICE_REFERENCE is not set, take the localhost name  
#
if [ "X$NAMESERVICE_REFERENCE" = "X" ]
then  
    ACS_NAMING_SERVICE_PORT=`getNamingServicePort`    
    export NAMESERVICE_REFERENCE=iiop://$HOST:$ACS_NAMING_SERVICE_PORT
fi

#
# Fetches port numbers
#      
export ACS_MANAGER_PORT=`getManagerPort`
export ACS_CDB_PORT=`getCDBPort`

if ! checkTCPPort $ACS_MANAGER_PORT
then
    ACS_LOG_ERROR "Manager port is being used by another process. Cannot continue!"
    exit $EC_NOPORT
fi
                                                         
ACS_LOG_DEBUG "ACS Naming Service: $NAMESERVICE_REFERENCE"
ACS_LOG_DEBUG "Manager will be run on port: $ACS_MANAGER_PORT"

#
# Evaluates properties for Manager federation
# The variable ACS_FEDERATION will remain empy if no federation
# is requested.
#
ACS_FEDERATION=""
if [ "X$ACS_DOMAINS" != "X" ]
then  
     ACS_FEDERATION="$ACS_FEDERATION -DACS.domains=$ACS_DOMAINS"
fi
if [ "X$ACS_FEDERATION_DIRECTORY" != "X" ]
then  
     ACS_FEDERATION="$ACS_FEDERATION -DACS.federationDirectory=$ACS_FEDERATION_DIRECTORY"
fi

#
# Evaluates property for DAL reference
# The variable ACS_DAL_REF will be set
#
ACS_DAL_REF=""
if [ "X$DAL_REFERENCE" != "X" ]
then
     ACS_DAL_REF="$DAL_REFERENCE"
else
     ACS_DAL_REF="corbaloc::$HOST:$ACS_CDB_PORT/CDB"
fi

#
# Set JVM_GC_LOG_NAME so that acsStartJava will run the JVM printing garbage collector details to file "jmanager.gclog".
# @TODO: When using several federated manager instances, we'll have to ensure that the jmanager.gclog files don't interfere with each other!
#
export JVM_GC_LOG_NAME=jmanager

#
# As of 2009-02, using acsStartJava instead of a custom classpath has worked well since ACS 7.0, so 
# that it becomes the only available choice here.
#
acsStartJava -endorsed \
    -Djacorb.poa.thread_pool_max=200 \
    -DNamingServiceRemoteDirectory.reference=$NAMESERVICE_REFERENCE \
    -DDAL.defaultReference=$ACS_DAL_REF \
    -DOAPort=$ACS_MANAGER_PORT \
    -Dmanager.debug.rememberOldHandles \
    $ACS_FEDERATION com.cosylab.acs.maci.manager.app.Manager $1 $2 $3 $4 $5 $6 $7 $8 $9
