#! /bin/sh
#*******************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) European Southern Observatory, 2002
# Copyright by ESO (in the framework of the ALMA collaboration)
# and Cosylab 2002, All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA 02111-1307  USA
#
# "@(#) $Id: jlog,v 1.30 2007/02/13 15:36:55 acaproni Exp $"
#
#acsStartJava com.cosylab.logging.LoggingClient

#
# GCH 2006-12-14
# JLog needs a special xmlparser when using
# Oracle and trying to retreives logs from the ARCHIVE
# We first search to see if it exist and, in case, we add it.
#
OracleXmlParser="lib/oracle/xmlparserv2.jar"
OracleXmlParserPath=`searchFile lib/oracle/xmlparserv2.jar`
if [ "$OracleXmlParserPath" != "#error#" ] 
then
    echo "Adding ORACLE XML parser jar to classpath: $OracleXmlParserPath/$OracleXmlParser"
    CLASSPATH=$CLASSPATH:$OracleXmlParserPath/$OracleXmlParser
fi
acsStartJava -v -Xms32m -v -Xmx512m --noDirectory alma.acs.logging.dialogs.main.LogFrame $*
