package alma.demo.EventConsumerImpl;

import java.util.logging.Logger;

import alma.acs.component.ComponentLifecycle;
import alma.acs.container.ComponentHelper;
import alma.demo.NCReceiverOperations;
import alma.demo.NCReceiverPOATie;

/**
 * @author  rtobar
 */
public class NCReceiverHelper extends ComponentHelper
{
	public NCReceiverHelper(Logger containerLogger)
	{
		super(containerLogger);
	}

    /** Method _createComponentImpl to be provided by subclasses.
     * Must return the same object that also implements the functional interface.
     *
     * @return ComponentLifecycle
     */
    protected ComponentLifecycle _createComponentImpl()
    {
        return new NCReceiverImpl();
    }

    /** This method must be provided by the component helper class.
     *
     * @return Class
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
	protected Class _getPOATieClass()
    {
        return NCReceiverPOATie.class;
    }

    /** Gets the xxOperations interface as generated by the IDL compiler.
     *
     * This method must be provided by the component helper class.
     *
     * @return  the <code>Class</code> object associated with the operations interface.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
	protected Class _getOperationsInterface()
    {
        return NCReceiverOperations.class;
    }
}
