#ifndef _RAMPEDPOWERSUPPLY_IDL_
#define _RAMPEDPOWERSUPPLY_IDL_

/*******************************************************************************
*    ALMA - Atacama Large Millimiter Array
*    (c) European Southern Observatory, 2002
*    Copyright by ESO (in the framework of the ALMA collaboration)
*    and Cosylab 2002, All rights reserved
*
*    This library is free software; you can redistribute it and/or
*    modify it under the terms of the GNU Lesser General Public
*    License as published by the Free Software Foundation; either
*    version 2.1 of the License, or (at your option) any later version.
*
*    This library is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*    Lesser General Public License for more details.
*
*    You should have received a copy of the GNU Lesser General Public
*    License along with this library; if not, write to the Free Software
*    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
*
* "@(#) $Id: acsexmplRampedPowerSupply.idl,v 1.81 2004/01/27 21:13:23 dfugate Exp $"
*
* who       when      what
* --------  --------  ----------------------------------------------
*/

#include <baci.idl>
#include <acsexmplPowerSupply.idl>

#pragma prefix "alma"

/** @file acsexmplRampedPowerSupply.idl
 *  RampedPowerSupply's IDL File
 */

module RampedPS 
{
    /** @interface RampedPowerSupply
     *  Interface RampedPowerSupply also implements PowerSupply.
     */
    interface RampedPowerSupply : PS::PowerSupply
	{
	/** 
	 *  Starts ramping asynchronously. That is, we are notified by the callback 
	 *  when the method really completes.
	 *  @param rampingSteps
	 *  @param cb callback when ramping is started.
	 *  @param desc is used to negotiate timeouts between client and sever.
	 *  See the BACI specifications for more details.
	 *  @return void
	 *  @htmlonly
	 *  <br><hr>
	 *  @endhtmlonly
	 */
	void startRamping(in long rampingSteps, in ACS::CBvoid cb, in ACS::CBDescIn desc);   
	
	/** 
	 *  Stops ramping asynchronously. That is, we are notified by the callback 
	 *  when the method really completes.
	 *  @param cb callback when ramping has stopped.
	 *  @param desc is used to negotiate timeouts between client and sever.
	 *  See the BACI specifications for more details.
	 *  @return void
	 *  @htmlonly
	 *  <br><hr>
	 *  @endhtmlonly
	 */
	void stopRamping(in ACS::CBvoid cb, in ACS::CBDescIn desc);                          
	
	/** This property states whether the power supply is ramping or not.
	 */
	readonly attribute ACS::RWstring rampingStatus;
	
	/** This property holds the current ramping step.
	 */
	readonly attribute ACS::ROlong rampingStep;
	};  
};

#endif
