#! /bin/bash
. acsstartupAcsPorts  #Import functions like this in bash=(
#*******************************************************************************
# E.S.O. - VLT project
#
# "@(#) $Id: acsStartLoggingClient,v 1.128 2006/06/22 05:04:59 cparedes Exp $"
#
# who       when      what
# --------  --------  ----------------------------------------------
# david 2003-05-14 now bash for tat
# gchiozzi 2001-09-19 created
#

#************************************************************************
#   NAME
# 
#   SYNOPSIS
# 
#   DESCRIPTION
#
#   FILES
#
#   ENVIRONMENT
#
#   RETURN VALUES
#
#   CAUTIONS
#
#   EXAMPLES
#
#   SEE ALSO
#
#   BUGS     
#
#------------------------------------------------------------------------
#

ACS_NAMING_SERVICE_PORT=`getNamingServicePort`

if [ "X$NAMESERVICE_REFERENCE" = "X" ]
then
    nameservice_corbaloc="corbaloc::$HOST:$ACS_NAMING_SERVICE_PORT/NameService"
else
    nameservice_corbaloc=$NAMESERVICE_REFERENCE
fi

loggingClient LoggingChannel -ORBInitRef NameService=$nameservice_corbaloc $1



#
# ___oOo___
