#! /bin/bash
cdbTATEpilogue > cdbTATEpilogue.log 2>&1


cp -r case-files/alma/COMP99 CDB/alma
cp -r case-files/MACI/Components/COMP99 CDB/MACI/Components
cp case-files/schemas/TESTCDB.xsd CDB/schemas

ACS_LOG_STDOUT=4
acsStart > acsStart.log 2>&1
sleep 10
acsutilAwaitContainerStart -cpp Container 
sleep 10
cdbInitMount
sleep 5
acsStop > acsStop.log 2>&1
sleep 2
grep "COMP99" acsStart.log
rm -rf CDB/alma/COMP99 CDB/MACI/Components/COMP99 CDB/schemas/TESTCDB.xsd

cdbTATPrologue > cdbTATPrologue.log 2>&1
