#! /bin/bash
#*******************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) Associated Universities Inc., 2002 
# (c) European Southern Observatory, 2002
# Copyright by ESO (in the framework of the ALMA collaboration)
# and Cosylab 2002, All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA 02111-1307  USA
#
# "@(#) $Id: acsstartupTATPrologue,v 1.3 2009/06/26 05:55:22 hyatagai Exp $"
#
# who       when      what
# --------  --------  ----------------------------------------------
# almamgr 2000-09-13 created
echo " ****************** TATPrologue ************* "

export ACS_CDB=$PWD
export ACS_LOG_STDOUT=4

# To be sure, deletes the recovery file before starting
acsdataClean

#creates the tmp directory if it doesn't exist
#the ACS_TMP variable is defined in acsstartupTATEnvironment
if [ ! -d $ACS_TMP ]; then
        mkdir -p $ACS_TMP
fi
    
