#! /bin/bash
export CLASSPATH=`vltMakeJavaClasspath`
export IP=`host $HOST | awk '{print $4}'`
qftestJUI -batch  -report.copyicons -report.depth 10 -report.html %b.html -systemcfg $HOME/qftestJUI.cfg -variable IP=$IP -variable HOST=$HOST -variable HOME=$HOME -libpath $HOME -runlog %b.qrz acscommandcenter.qft
echo $?
