#ifndef _TMCBD_MONITOR_COLLECTOR_
#define _TMCBD_MONITOR_COLLECTOR_

#include <acscommon.idl>
#include <acscomponent.idl>
#include <TMCDBCOMMON_IDL.idl>

#include "MonitorErr.idl"

#pragma prefix "alma"


module TMCDB
{

struct propertySerailNumber
{
	string  propertyName;
	serialNumberTypeSeq  serialNumbers;
};

typedef sequence<propertySerailNumber> propertySerialNumberSeq; 


 interface MonitorCollector : ACS::ACSComponent
    {
    /// methods for a component/device
    void registerMonitoredDevice(in string componentName, in serialNumberType serialNumber) 
    	raises (MonitorErr::DeviceAlreadyRegisteredEx, MonitorErr::RegisteringDeviceProblemEx); /// Called by device (MonCol gets non-sticky reference)
    	
	void registerMonitoredDeviceWithMultipleSerial(in string componentName, in  propertySerialNumberSeq serialNumbers) 
    	raises (MonitorErr::DeviceAlreadyRegisteredEx, MonitorErr::RegisteringDeviceProblemEx); /// Called by device (MonCol gets non-sticky reference)
    	    	
    void deregisterMonitoredDevice(in string componentName)
    	raises(MonitorErr::DeviceNotRegisteredEx);
    
    void startMonitoring(in string componentName) raises(MonitorErr::StartMonitoringProblemEx);
    
    void stopMonitoring(in string componentName) raises (MonitorErr::StopMonitoringProblemEx);

	///for the archiver or better monitor controler
    MonitorDataBlocks getMonitorData();  

    void set_archiving_interval(in string componentName, in string propertyName, in ACS::TimeInterval time);

    void suppress_archiving(in string componentName, in string propertyName);

    void enable_archiving(in string componentName, in string propertyName);
    };//interface MonitorCollector


};//module  TMCDB

#endif
