#! /bin/bash
#*******************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) European Southern Observatory, 2002
# Copyright by ESO (in the framework of the ALMA collaboration),
# All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307  USA
#
# "@(#) $Id: jbaciTATPrologue,v 1.2 2008/04/11 15:42:47 hsommer Exp $"
#
# who       when      what
# --------  --------  ----------------------------------------------


echo " ****************** jbaciTATPrologue ************* "
ACS_CDB=$PWD

echo " Staring ORB Services and Manager"
acsutilTATPrologue -l

echo " Starting C++ Container"
acsutilAwaitContainerStart -cpp Container01

echo " Starting Java Container"
export JAVA_OPTIONS="-Dacs.container.fakeUIDsForTesting=true"
acsutilAwaitContainerStart -java frodoContainer

