#ifndef _LAMPCALLBACK_IDL_
#define _LAMPCALLBACK_IDL_
/*
 *    ALMA - Atacama Large Millimiter Array
 *    (c) European Southern Observatory, 2002
 *    Copyright by ESO (in the framework of the ALMA collaboration),
 *    All rights reserved
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 2.1 of the License, or (at your option) any later version.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
 *    MA 02111-1307  USA
 */

#include <acserr.idl>
#include <LampAccess.idl>
#include <acscomponent.idl>

#pragma prefix "alma"

module demo
{ 
 	interface LampCallback : ACS::ACSComponent
	{
		double monitorLampBrightness() raises (LampUnavailable);
		
		void stopMonitor() raises (LampUnavailable);


		// will always throw a plain-CORBA LampUnavailable exception 
		void exceptionMethod() raises (LampUnavailable);
		
		// will throw an ACSException
	    void acsExceptionMethodVoid() raises (ACSErr::ACSException);
	    double acsExceptionMethodDouble() raises (ACSErr::ACSException);
	};
};

#endif
