#ifndef _BULKDATA_SENDRECV_IDL_
#define _BULKDATA_SENDRECV_IDL_

/*******************************************************************************
*    ALMA - Atacama Large Millimiter Array
*
*    (c) European Southern Observatory, 2002
*    Copyright by ESO (in the framework of the ALMA collaboration)
*    and Cosylab 2002, All rights reserved
*
*    This library is free software; you can redistribute it and/or
*    modify it under the terms of the GNU Lesser General Public
*    License as published by the Free Software Foundation; either
*    version 2.1 of the License, or (at your option) any later version.
*
*    This library is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*    Lesser General Public License for more details.
*
*    You should have received a copy of the GNU Lesser General Public
*    License along with this library; if not, write to the Free Software
*    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
*
*
* "@(#)"
*
* who       when      what
* --------  --------  ----------------------------------------------
* oat       27/01/05  created
*/

#include <baci.idl>
#include <ACSBulkDataError.idl>
#include <AVStreams.idl>
#include <bulkData.idl>
#include <bulkDataReceiver.idl>
#include <bulkDataSender.idl>

#pragma prefix "alma"

/** @file bulkDataSendRecv.idl
 *  Bulk Data SendRecv IDL File (SendRecv Component).
 */

module bulkdata
{
    
  /** @interface BulkDataSendRecv
   *  Defines the interface for the Bulk Data SendRecv Component
   */
  interface BulkDataSendRecv : bulkdata::BulkDataReceiver, bulkdata::BulkDataSender
  {
  };

};

#endif
