#!/bin/bash 
#
# Script to automatically install Ant
#
# who       when       what
# --------  ---------  ----------------------------------------------
# psivera   24/04/2003 created
# sturolla  09/09/2005 ported to Bourne Shell and OS checks is done by an external subroutine
# hsommer   08/07/2007 Update to ANT 1.7 for ACS 7.0
#

# Load functions
. standardUtilities
#
# Fetch operating system and release version
#
os_discovery

# Some default values
#

Install_Ant()
{
    if [ -z "$ANT_HOME" ]
    then
        echo "ANT_HOME is not set, cannot continue.\n"
        exit 1
    fi

    if [ ! -d $ANT_HOME ]
    then
        mkdir -p $ANT_HOME
        RET=$?
        if [ $RET -ne 0 ]
        then
            echo "Failed to create $ANT_HOME, cannot continue..."
            exit 1
        fi
    fi
    
    JAR_ARCHIVE=`pwd`/../PRODUCTS/apache-ant-jars 

    ANT_VERSION=1.9.3
    echo "Now installing Ant $ANT_VERSION... \c"
    tar xzf ../PRODUCTS/apache-ant-$ANT_VERSION-src.tar.gz --directory $ANT_HOME/..
    ANT_UNPACKED_DIR=$ANT_HOME/../apache-ant-$ANT_VERSION
    cd $ANT_UNPACKED_DIR
    cp $JAR_ARCHIVE/junit-4.11.jar lib/optional/
    cp $JAR_ARCHIVE/hamcrest-core-1.3.jar lib/optional/
# TODO: 'dist-lite' produces a minimum installation in $ANT_HOME, so we might want to add sources ('jars-sources'? etc)
    sh build.sh -Ddist.dir=$ANT_HOME dist-lite || exit 1
    sh build.sh test || exit 1
    rm -rf $ANT_UNPACKED_DIR
    echo "done.\n"

}



######################################################################
#                                                                    #
# Execution starts here!                                             #
#                                                                    #
######################################################################

LOG=buildAnt.log
#
exec > $LOG 2>&1

date

CURR_DIR=`pwd`

#
# It build and install the archive
#
Install_Ant

#
cd $CURR_DIR

echo Ant installation done!
date
