#! /bin/bash
#*******************************************************************************
# E.S.O. - ALMA project
#
# "@(#) $Id$"
#
# who        when        what
# --------   ----------  ----------------------------------------------
# agrimstrup 2007-07-10  created
#

#************************************************************************
#   NAME
#
#   SYNOPSIS
#
#   DESCRIPTION
#
#   FILES
#
#   ENVIRONMENT
#
#   RETURN VALUES
#
#   CAUTIONS
#
#   EXAMPLES
#
#   SEE ALSO
#
#   BUGS
#
#------------------------------------------------------------------------
#

#
# Install Python Modules
#
#set -x
#export PYTHON_ROOT=/alma/$ALMASW_RELEASE/Python

# Load functions
. standardUtilities
#
# Fetch operating system and release version
#
os_discovery


LOG=buildPyModules.log
CWD=`pwd`
#
exec > $LOG 2>&1

date

if [ ! -d $PYTHON_ROOT ]
then
  echo "$PYTHON_ROOT not found, cannot continue..."
  exit 1
fi

echo installing Python Modules

echo $SEPARATOR
if [ ${OS} = "LINUX" ] 
then
	echo "Installing on $DISTRO $OS version $REL"
else
	echo "Installing on $OS version $REL"
fi

if [     ${DISTRO}-${REL} != "SOLARIS-5.8"       \
     -a  ${DISTRO}-${REL} != "RHLX-7.2"           \
     -a  ${DISTRO}-${REL} != "RHLX-7.3"           \
     -a  ${DISTRO}-${REL} != "RHLX-9"           \
     -a  ${DISTRO}-${REL} != "RHEL-4"           \
     -a  ${DISTRO}-${REL} != "SL-4.1"           \
   ]
then
    echo "OS not supported. Proceeding as for Linux RH 9"
    echo ""
fi

#
# Python - Python-2.5.2
#
# Notes: See README for help
#
cd ../PRODUCTS

if [ ! -e ../PRODUCTS/setuptools-0.6c8.tar.gz ]
then
  echo Error: setuptools sources are missing
else
  echo "== Building setuptools"
  tar -zxvf setuptools-0.6c8.tar.gz
  pushd setuptools-0.6c8
  python setup.py install
  popd
fi


if [ ! -e ../PRODUCTS/pysnmp-2.0.9.tar.gz ]
then
  echo Error: PySNMP sources are missing
else
  echo "== Building PySNMP"
  tar -zxvf pysnmp-2.0.9.tar.gz
  pushd pysnmp-2.0.9
  python setup.py install
  popd
fi


if [ ! -e ../PRODUCTS/python-ldap-2.3.5.tar.gz ]
then
  echo Error: Python LDAP sources are missing
else
  echo "== Building Python LDAP"
  tar -zxvf python-ldap-2.3.5.tar.gz
  pushd python-ldap-2.3.5
  cat setup.cfg | sed 's/local\/openldap-REL_ENG_2_1\///' >> setup.cfg.tmp
  mv setup.cfg.tmp setup.cfg 
  python setup.py install
  popd
fi

if [ ! -e ../PRODUCTS/Numeric-24.2.tar.gz ]
then
  echo Error: Numeric sources are missing
else
  echo "== Building Numeric"
  tar -zxvf Numeric-24.2.tar.gz
  pushd Numeric-24.2
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/numpy-1.1.1.tar.gz ]
then
  echo Error: numpy sources are missing
else
  echo "== Building numpy"
  export BLAS=/usr/lib/libblas.so
  export LAPACK=/usr/lib/liblapack.so
  tar -zxvf numpy-1.1.1.tar.gz
  pushd numpy-1.1.1
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/gnuplot-py-1.8.tar.gz ]
then
  echo Error: GnuPlot Py sources are missing
else
  echo "== Building GnuPlot Py"
  tar -zxvf gnuplot-py-1.8.tar.gz
  pushd gnuplot-py-1.8
  python setup.py install
  popd
fi

if [ ! -e ../PRODUCTS/matplotlib-0.91.4.tar.gz ]
then
  echo Error: matplotlib sources are missing
else
  echo "== Building matplotlib"
  tar -zxvf matplotlib-0.91.4.tar.gz;
  pushd matplotlib-0.91.4

  cat setupext.py | sed s/\'linux2\'\ :\ \\[/\'linux2\'\ :\ \\[os.environ\\[\'PYTHON_ROOT\'\\],/g >> setupext.py.tmp
  mv setupext.py.tmp setupext.py

  cat setup.py | sed s/BUILD_GTKAGG\ \ \ \ \ \ \ =\ \'auto\'/BUILD_GTKAGG=0/g >> setup.py.tmp
  mv setup.py.tmp setup.py

  cat setup.py | sed s/BUILD_GTK\ \ \ \ \ \ \ \ \ \ =\ \'auto\'/BUILD_GTK=0/g >> setup.py.tmp
  mv setup.py.tmp setup.py

  cat setup.py | sed s/BUILD_TKAGG\ \ \ \ \ \ \ \ =\ \'auto\'/BUILD_TKAGG=1/g >> setup.py.tmp
  mv setup.py.tmp setup.py

  export BUILD_AGG=1
  python setup.py build
  python setup.py install 


  echo "== Configuring matplotlib"
  if [ ! -e ${PYTHON_ROOT}/share ]
  then
    mkdir ${PYTHON_ROOT}/share
    mkdir ${PYTHON_ROOT}/share/matplotlib
  elif [ ! -e ${PYTHON_ROOT}/share/matplotlib ]
  then
    mkdir ${PYTHON_ROOT}/share/matplotlib
  fi
  cp ${PYTHON_ROOT}/lib/python2.5/site-packages/matplotlib/mpl-data/matplotlibrc ${PYTHON_ROOT}/share/matplotlib/.matplotlibrc
  pushd ${PYTHON_ROOT}/share/matplotlib/ 
  cat .matplotlibrc | sed s/numerix\ \ \ \ \ \ :\ Numeric/numerix\ \ \ \ \ \ :\ numarray/g >> .matplotlibrc.tmp
  mv .matplotlibrc.tmp .matplotlibrc
  cat .matplotlibrc | sed s/backend\ \ \ \ \ \ :\ GTKAgg/backend\ \ \ \ \ \ :\ TkAgg/g >> .matplotlibrc.tmp
  mv .matplotlibrc.tmp .matplotlibrc
  cat .matplotlibrc | sed s/#interactive\ \ :\ False/interactive\ \ :\ True/g >> .matplotlibrc.tmp
  mv .matplotlibrc.tmp .matplotlibrc
  popd
  popd
fi

if [ ! -e ../PRODUCTS/scipy-0.6.0.tar.gz ]
then
  echo Error: numpy sources are missing
else
  echo "== Building scipy"
  tar -zxvf scipy-0.6.0.tar.gz
  pushd scipy-0.6.0
  python setup.py install 
  popd
fi

#if [ ! -e ../PRODUCTS/ipython1-saw.tar.gz \
#     -o ! -e ../PRODUCTS/Twisted-2.5.0.tar.bz2 \
#   ]
#then
#  echo Error: ipython1 sources are missing
#else
#  echo "== Building ipython1"
#  tar -jxvf Twisted-2.5.0.tar.bz2
#  pushd Twisted-2.5.0
#  pushd zope.interface-3.3.0
#  python setup.py install
#  popd
#  python setup.py install
#  popd
#  tar -zxvf ipython1-saw.tar.gz
#  pushd ipython1-saw
#  python setup.py install 
#  popd
#fi

if [ ! -e ../PRODUCTS/pexpect-2.3.tar.gz ]
then
  echo Error: pexpect sources are missing
else
  echo "== Building pexpect"
  tar -zxvf pexpect-2.3.tar.gz
  pushd pexpect-2.3
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/pychecker-0.8.17.tar.gz ]
then
  echo Error: pychecker sources are missing
else
  echo "== Building pychecker"
  tar -zxvf pychecker-0.8.17.tar.gz
  pushd pychecker-0.8.17
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/coverage-2.80.tar.gz ]
then
  echo Error: coverage sources are missing
else
  echo "== Building coverage"
  tar -zxvf coverage-2.80.tar.gz
  pushd coverage-2.80
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/mock-0.4.0.zip ]
then
  echo Error: Python Mock sources are missing
else
  echo "== Installing Python Mock Objects"
  unzip -oj mock-0.4.0.zip mock-0.4.0/mock.py mock-0.4.0/testcase.py mock-0.4.0/testutils.py -d $PYTHON_ROOT/lib/python2.5/site-packages/
fi

if [ ! -e ../PRODUCTS/generateDS-1.15d.tar.gz ]
then
  echo Error: generateDS sources are missing
else
  echo "== Installing generateDS"
  tar -zxvf generateDS-1.15d.tar.gz
  pushd generateDS-1.15d
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/snakefood-1.3.1.tar.bz2 ]
then
  echo Error: snakefood sources are missing
else
  echo "== Installing snakefood"
  tar -jxvf snakefood-1.3.1.tar.bz2
  pushd snakefood-1.3.1
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/figleaf-latest.tar.gz ]
then
  echo Error: figleaf sources are missing
else
  echo "== Installing figleaf"
  tar -zxvf figleaf-latest.tar.gz
  pushd figleaf-latest
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/pythoscope-0.3.2.tar.gz ]
then
  echo Error: Pythoscope sources are missing
else
  echo "== Installing Pythoscope"
  tar -zxvf pythoscope-0.3.2.tar.gz
  pushd pythoscope-0.3.2
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/lxml-2.1.5.tar.gz ]
then
  echo Error: lxml sources are missing
else
  echo "== Installing lxml"
  tar -zxvf lxml-2.1.5.tar.gz
  pushd lxml-2.1.5
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/nose-0.10.4.tar.gz ]
then
  echo Error: nose sources are missing
else
  echo "== Installing nose"
  tar -zxvf nose-0.10.4.tar.gz
  pushd nose-0.10.4
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/pylint-0.18.0.tar.gz \
     -o ! -e ../PRODUCTS/logilab-astng-0.19.0.tar.gz \
     -o ! -e ../PRODUCTS/logilab-common-0.39.0.tar.gz
   ]
then
  echo Error: pylint sources are missing
else
  echo "== Building pylint"
  tar -xvzf logilab-common-0.39.0.tar.gz
  pushd logilab-common-0.39.0
  python setup.py install
  popd
  tar -xvzf logilab-astng-0.19.0.tar.gz
  pushd logilab-astng-0.19.0
  python setup.py install
  popd
  tar -zxvf pylint-0.18.0.tar.gz
  pushd pylint-0.18.0
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/ipython-0.9.1.tar.gz \
     -o ! -e ../PRODUCTS/Twisted-8.2.0.tar.bz2 \
     -o ! -e ../PRODUCTS/zope.interface-3.5.1.tar.gz \
     -o ! -e ../PRODUCTS/Sphinx-0.6.1.tar.gz \
     -o ! -e ../PRODUCTS/pyOpenSSL-0.9.tar.gz \
     -o ! -e ../PRODUCTS/Pygments-1.0.tar.gz \
     -o ! -e ../PRODUCTS/foolscap-0.4.1.tar.gz \
     -o ! -e ../PRODUCTS/Jinja2-2.1.1.tar.gz \
     -o ! -e ../PRODUCTS/docutils-snapshot.tgz \
]
then
  echo Error: ipython sources are missing
else
  echo "== Building IPython"
  tar -zxvf Pygments-1.0.tar.gz
  pushd Pygments-1.0
  python setup.py install 
  popd
  tar -zxvf Jinja2-2.1.1.tar.gz
  pushd Jinja2-2.1.1
  python setup.py install 
  popd
  tar -zxvf docutils-snapshot.tgz
  pushd docutils
  python setup.py install 
  popd
  tar -zxvf Sphinx-0.6.1.tar.gz
  pushd Sphinx-0.6.1
  python setup.py install 
  popd
  tar -zxvf zope.interface-3.5.1.tar.gz
  pushd zope.interface-3.5.1
  python setup.py install 
  popd
  tar -jxvf Twisted-8.2.0.tar.bz2
  pushd Twisted-8.2.0
  python setup.py install 
  popd
  tar -zxvf pyOpenSSL-0.9.tar.gz
  pushd pyOpenSSL-0.9
  python setup.py install 
  popd
  tar -zxvf foolscap-0.4.1.tar.gz
  pushd foolscap-0.4.1
  python setup.py install 
  popd
  tar -zxvf ipython-0.9.1.tar.gz
  pushd ipython-0.9.1
  python setup.py install 
  popd
fi

cd $CWD
echo Python Module installation done!
date

