#! /bin/bash
#*******************************************************************************
# E.S.O. - ALMA project
#
# "@(#) $Id$"
#
# who        when        what
# --------   ----------  ----------------------------------------------
# agrimstrup 2007-07-10  created
#

#************************************************************************
#   NAME
#
#   SYNOPSIS
#
#   DESCRIPTION
#
#   FILES
#
#   ENVIRONMENT
#
#   RETURN VALUES
#
#   CAUTIONS
#
#   EXAMPLES
#
#   SEE ALSO
#
#   BUGS
#
#------------------------------------------------------------------------
#

#
# Install Python Modules
#
#set -x
#export PYTHON_ROOT=/alma/$ALMASW_RELEASE/Python

# Load functions
. standardUtilities
#
# Fetch operating system and release version
#
os_discovery


LOG=buildPyModules.log
CWD=`pwd`
#
exec > $LOG 2>&1

date

if [ ! -d $PYTHON_ROOT ]
then
  echo "$PYTHON_ROOT not found, cannot continue..."
  exit 1
fi

echo installing Python Modules

echo $SEPARATOR
if [ ${OS} = "LINUX" ] 
then
	echo "Installing on $DISTRO $OS version $REL"
else
	echo "Installing on $OS version $REL"
fi

if [     ${DISTRO}-${REL} != "SOLARIS-5.8"       \
     -a  ${DISTRO}-${REL} != "RHLX-7.2"           \
     -a  ${DISTRO}-${REL} != "RHLX-7.3"           \
     -a  ${DISTRO}-${REL} != "RHLX-9"           \
     -a  ${DISTRO}-${REL} != "RHEL-4"           \
     -a  ${DISTRO}-${REL} != "SL-4.1"           \
   ]
then
    echo "OS not supported. Proceeding as for Linux RH 9"
    echo ""
fi

#
# Python - Python-2.4.1
#
# Notes: See README for help
#
cd ../PRODUCTS

if [ ! -e ../PRODUCTS/setuptools-0.6c6.tar.gz ]
then
  echo Error: setuptools sources are missing
else
  echo "== Building setuptools"
  tar -zxvf setuptools-0.6c6.tar.gz
  pushd setuptools-0.6c6
  python setup.py install
  popd
fi


if [ ! -e ../PRODUCTS/pysnmp-2.0.9.tar.gz ]
then
  echo Error: PySNMP sources are missing
else
  echo "== Building PySNMP"
  tar -zxvf pysnmp-2.0.9.tar.gz
  pushd pysnmp-2.0.9
  python setup.py install
  popd
fi


if [ ! -e ../PRODUCTS/python-ldap-2.0.1.tar.gz ]
then
  echo Error: Python LDAP sources are missing
else
  echo "== Building Python LDAP"
  tar -zxvf python-ldap-2.0.1.tar.gz
  pushd python-ldap-2.0.1
  cat setup.cfg | sed 's/local\/openldap-REL_ENG_2_1\///' >> setup.cfg.tmp
  mv setup.cfg.tmp setup.cfg 
  python setup.py install
  popd
fi

if [ ! -e ../PRODUCTS/Numeric-24.2.tar.gz ]
then
  echo Error: Numeric sources are missing
else
  echo "== Building Numeric"
  tar -zxvf Numeric-24.2.tar.gz
  pushd Numeric-24.2
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/numarray-1.5.2.tar.gz ]
then
  echo Error: numarray sources are missing
else
  echo "== Building numarray"
  tar -zxvf numarray-1.5.2.tar.gz
  pushd numarray-1.5.2
  python setup.py install --gencode 
  popd
fi

if [ ! -e ../PRODUCTS/numpy-1.0.3.1.tar.gz ]
then
  echo Error: numpy sources are missing
else
  echo "== Building numpy"
  export BLAS=/usr/lib/libblas.so
  export LAPACK=/usr/lib/liblapack.so
  tar -zxvf numpy-1.0.3.1.tar.gz
  pushd numpy-1.0.3.1
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/gnuplot-py-1.7.tar.gz ]
then
  echo Error: GnuPlot Py sources are missing
else
  echo "== Building GnuPlot Py"
  tar -zxvf gnuplot-py-1.7.tar.gz
  pushd gnuplot-py-1.7
  python setup.py install
  popd
fi

if [ ! -e ../PRODUCTS/matplotlib-0.90.1.tar.gz ]
then
  echo Error: matplotlib sources are missing
else
  echo "== Building matplotlib"
  tar -zxvf matplotlib-0.90.1.tar.gz;
  pushd matplotlib-0.90.1

  cat setupext.py | sed s/\'linux2\'\ :\ \\[/\'linux2\'\ :\ \\[os.environ\\[\'PYTHON_ROOT\'\\],/g >> setupext.py.tmp
  mv setupext.py.tmp setupext.py

  cat setup.py | sed s/BUILD_GTKAGG\ \ \ \ \ \ \ =\ \'auto\'/BUILD_GTKAGG=0/g >> setup.py.tmp
  mv setup.py.tmp setup.py

  cat setup.py | sed s/BUILD_GTK\ \ \ \ \ \ \ \ \ \ =\ \'auto\'/BUILD_GTK=0/g >> setup.py.tmp
  mv setup.py.tmp setup.py

  cat setup.py | sed s/BUILD_TKAGG\ \ \ \ \ \ \ \ =\ \'auto\'/BUILD_TKAGG=1/g >> setup.py.tmp
  mv setup.py.tmp setup.py

  export BUILD_AGG=1
  python setup.py build
  python setup.py install 


  echo "== Configuring matplotlib"
  if [ ! -e ${PYTHON_ROOT}/share ]
  then
    mkdir ${PYTHON_ROOT}/share
    mkdir ${PYTHON_ROOT}/share/matplotlib
  elif [ ! -e ${PYTHON_ROOT}/share/matplotlib ]
  then
    mkdir ${PYTHON_ROOT}/share/matplotlib
  fi
  cp ${PYTHON_ROOT}/lib/python2.5/site-packages/matplotlib/mpl-data/matplotlibrc ${PYTHON_ROOT}/share/matplotlib/.matplotlibrc
  pushd ${PYTHON_ROOT}/share/matplotlib/ 
  cat .matplotlibrc | sed s/numerix\ \ \ \ \ \ :\ Numeric/numerix\ \ \ \ \ \ :\ numarray/g >> .matplotlibrc.tmp
  mv .matplotlibrc.tmp .matplotlibrc
  cat .matplotlibrc | sed s/backend\ \ \ \ \ \ :\ GTKAgg/backend\ \ \ \ \ \ :\ TkAgg/g >> .matplotlibrc.tmp
  mv .matplotlibrc.tmp .matplotlibrc
  cat .matplotlibrc | sed s/#interactive\ \ :\ False/interactive\ \ :\ True/g >> .matplotlibrc.tmp
  mv .matplotlibrc.tmp .matplotlibrc
  popd
  popd
fi

if [ ! -e ../PRODUCTS/scipy-0.5.2.1.tar.gz ]
then
  echo Error: numpy sources are missing
else
  echo "== Building scipy"
  tar -zxvf scipy-0.5.2.1.tar.gz
  pushd scipy-0.5.2.1
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/ipython-0.8.1.tar.gz ]
then
  echo Error: ipython sources are missing
else
  echo "== Building IPython"
  tar -zxvf ipython-0.8.1.tar.gz
  pushd ipython-0.8.1
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/ipython1-saw.tar.gz \
     -o ! -e ../PRODUCTS/Twisted-2.5.0.tar.bz2 \
   ]
then
  echo Error: ipython1 sources are missing
else
  echo "== Building ipython1"
  tar -jxvf Twisted-2.5.0.tar.bz2
  pushd Twisted-2.5.0
  pushd zope.interface-3.3.0
  python setup.py install
  popd
  python setup.py install
  popd
  tar -zxvf ipython1-saw.tar.gz
  pushd ipython1-saw
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/pexpect-2.1.tar.gz ]
then
  echo Error: pexpect sources are missing
else
  echo "== Building pexpect"
  tar -zxvf pexpect-2.1.tar.gz
  pushd pexpect-2.1
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/pychecker-0.8.17.tar.gz ]
then
  echo Error: pychecker sources are missing
else
  echo "== Building pychecker"
  tar -zxvf pychecker-0.8.17.tar.gz
  pushd pychecker-0.8.17
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/coverage-2.77.tar.gz ]
then
  echo Error: coverage sources are missing
else
  echo "== Building coverage"
  tar -zxvf coverage-2.77.tar.gz
  pushd coverage-2.77
  python setup.py install 
  popd
fi

if [ ! -e ../PRODUCTS/pythonmock-0.1.0.zip ]
then
  echo Error: Python Mock sources are missing
else
  echo "== Installing Python Mock Objects"
  unzip -o pythonmock-0.1.0.zip *.py -d $PYTHON_ROOT/lib/python2.5/site-packages/
fi

cd $CWD
echo Python Module installation done!
date

