From the internet site, one should download the SDK kit. 
For ACS 3.0 we choose the J2SE v1.4.2 without NetBeans IDE v3.5 Cobundle
For linux: 
Linux self-extracting file 
For Solaris: 
Solaris SPARC 64-bit self-extracting file 
Normally it needs the analogous 32-bit file

The file for Linux has extension "bin" , for java "sh". 
The best way of doing is to execute the two self-extracting packages 
and recreate an archive with extension .tar.gz. 
Then modify accordingly the buildJava

For ACS 3.1 we keep the same Java version
