package alma.acs.tmcdb;
// Generated Jun 5, 2017 7:15:51 PM by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * AcaCorrDelays generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="`ACACORRDELAYS`"
)
public class AcaCorrDelays extends alma.acs.tmcdb.translator.TmcdbObject implements java.io.Serializable {


     protected Integer antennaId;
     protected Antenna antenna;
     protected Double bbOneDelay;
     protected Double bbTwoDelay;
     protected Double bbThreeDelay;
     protected Double bbFourDelay;
     protected Boolean locked;
     protected Boolean increaseVersion;
     protected Integer currentVersion;
     protected String who;
     protected String changeDesc;

    public AcaCorrDelays() {
    }
   
       @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="antenna"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="`ANTENNAID`", unique=true, nullable=false)
    public Integer getAntennaId() {
        return this.antennaId;
    }
    
    public void setAntennaId(Integer antennaId) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("antennaId", this.antennaId, this.antennaId = antennaId);
        else
            this.antennaId = antennaId;
    }


@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Antenna getAntenna() {
        return this.antenna;
    }
    
    public void setAntenna(Antenna antenna) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("antenna", this.antenna, this.antenna = antenna);
        else
            this.antenna = antenna;
    }


    
    @Column(name="`BBONEDELAY`", nullable=false, precision=64, scale=0)
    public Double getBbOneDelay() {
        return this.bbOneDelay;
    }
    
    public void setBbOneDelay(Double bbOneDelay) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("bbOneDelay", this.bbOneDelay, this.bbOneDelay = bbOneDelay);
        else
            this.bbOneDelay = bbOneDelay;
    }


    
    @Column(name="`BBTWODELAY`", nullable=false, precision=64, scale=0)
    public Double getBbTwoDelay() {
        return this.bbTwoDelay;
    }
    
    public void setBbTwoDelay(Double bbTwoDelay) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("bbTwoDelay", this.bbTwoDelay, this.bbTwoDelay = bbTwoDelay);
        else
            this.bbTwoDelay = bbTwoDelay;
    }


    
    @Column(name="`BBTHREEDELAY`", nullable=false, precision=64, scale=0)
    public Double getBbThreeDelay() {
        return this.bbThreeDelay;
    }
    
    public void setBbThreeDelay(Double bbThreeDelay) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("bbThreeDelay", this.bbThreeDelay, this.bbThreeDelay = bbThreeDelay);
        else
            this.bbThreeDelay = bbThreeDelay;
    }


    
    @Column(name="`BBFOURDELAY`", nullable=false, precision=64, scale=0)
    public Double getBbFourDelay() {
        return this.bbFourDelay;
    }
    
    public void setBbFourDelay(Double bbFourDelay) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("bbFourDelay", this.bbFourDelay, this.bbFourDelay = bbFourDelay);
        else
            this.bbFourDelay = bbFourDelay;
    }


    
    @Column(name="`LOCKED`")
    public Boolean getLocked() {
        return this.locked;
    }
    
    public void setLocked(Boolean locked) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("locked", this.locked, this.locked = locked);
        else
            this.locked = locked;
    }


    
    @Column(name="`INCREASEVERSION`")
    public Boolean getIncreaseVersion() {
        return this.increaseVersion;
    }
    
    public void setIncreaseVersion(Boolean increaseVersion) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("increaseVersion", this.increaseVersion, this.increaseVersion = increaseVersion);
        else
            this.increaseVersion = increaseVersion;
    }


    
    @Column(name="`CURRENTVERSION`")
    public Integer getCurrentVersion() {
        return this.currentVersion;
    }
    
    public void setCurrentVersion(Integer currentVersion) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("currentVersion", this.currentVersion, this.currentVersion = currentVersion);
        else
            this.currentVersion = currentVersion;
    }


    
    @Column(name="`WHO`", length=128)
    public String getWho() {
        return this.who;
    }
    
    public void setWho(String who) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("who", this.who, this.who = who);
        else
            this.who = who;
    }


    
    @Column(name="`CHANGEDESC`", length=16777216)
    public String getChangeDesc() {
        return this.changeDesc;
    }
    
    public void setChangeDesc(String changeDesc) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("changeDesc", this.changeDesc, this.changeDesc = changeDesc);
        else
            this.changeDesc = changeDesc;
    }





}


