package alma.acs.tmcdb;
// Generated Jun 5, 2017 7:15:51 PM by Hibernate Tools 4.3.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BL_Antenna generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="`BL_ANTENNA`"
)
public class BL_Antenna extends alma.acs.tmcdb.translator.TmcdbObject implements java.io.Serializable {


     protected BL_AntennaId id;
     protected String who;
     protected String changeDesc;
     protected String antennaType;
     protected Double dishDiameter;
     protected Long commissionDate;
     protected Double XPosition;
     protected Double YPosition;
     protected Double ZPosition;
     protected Double XOffset;
     protected Double YOffset;
     protected Double ZOffset;
     protected Integer LOOffsettingIndex;
     protected Integer walshSeq;
     protected Integer caiBaseline;
     protected Integer caiAca;

    public BL_Antenna() {
    }
   
       @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="`version`", column=@Column(name="VERSION`", nullable=false) ), 
        @AttributeOverride(name="modTime`", column=@Column(name="MODTIME`", nullable=false) ), 
        @AttributeOverride(name="operation`", column=@Column(name="OPERATION`", nullable=false, length=1) ), 
        @AttributeOverride(name="baseElementId`", column=@Column(name="BASEELEMENTID`", nullable=false) ) } )
    public BL_AntennaId getId() {
        return this.id;
    }
    
    public void setId(BL_AntennaId id) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("id", this.id, this.id = id);
        else
            this.id = id;
    }


    
    @Column(name="`WHO`", length=128)
    public String getWho() {
        return this.who;
    }
    
    public void setWho(String who) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("who", this.who, this.who = who);
        else
            this.who = who;
    }


    
    @Column(name="`CHANGEDESC`", length=16777216)
    public String getChangeDesc() {
        return this.changeDesc;
    }
    
    public void setChangeDesc(String changeDesc) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("changeDesc", this.changeDesc, this.changeDesc = changeDesc);
        else
            this.changeDesc = changeDesc;
    }


    
    @Column(name="`ANTENNATYPE`", nullable=false, length=16777216)
    public String getAntennaType() {
        return this.antennaType;
    }
    
    public void setAntennaType(String antennaType) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("antennaType", this.antennaType, this.antennaType = antennaType);
        else
            this.antennaType = antennaType;
    }


    
    @Column(name="`DISHDIAMETER`", nullable=false, precision=64, scale=0)
    public Double getDishDiameter() {
        return this.dishDiameter;
    }
    
    public void setDishDiameter(Double dishDiameter) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("dishDiameter", this.dishDiameter, this.dishDiameter = dishDiameter);
        else
            this.dishDiameter = dishDiameter;
    }


    
    @Column(name="`COMMISSIONDATE`", nullable=false)
    public Long getCommissionDate() {
        return this.commissionDate;
    }
    
    public void setCommissionDate(Long commissionDate) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("commissionDate", this.commissionDate, this.commissionDate = commissionDate);
        else
            this.commissionDate = commissionDate;
    }


    
    @Column(name="`XPOSITION`", nullable=false, precision=64, scale=0)
    public Double getXPosition() {
        return this.XPosition;
    }
    
    public void setXPosition(Double XPosition) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("XPosition", this.XPosition, this.XPosition = XPosition);
        else
            this.XPosition = XPosition;
    }


    
    @Column(name="`YPOSITION`", nullable=false, precision=64, scale=0)
    public Double getYPosition() {
        return this.YPosition;
    }
    
    public void setYPosition(Double YPosition) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("YPosition", this.YPosition, this.YPosition = YPosition);
        else
            this.YPosition = YPosition;
    }


    
    @Column(name="`ZPOSITION`", nullable=false, precision=64, scale=0)
    public Double getZPosition() {
        return this.ZPosition;
    }
    
    public void setZPosition(Double ZPosition) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("ZPosition", this.ZPosition, this.ZPosition = ZPosition);
        else
            this.ZPosition = ZPosition;
    }


    
    @Column(name="`XOFFSET`", nullable=false, precision=64, scale=0)
    public Double getXOffset() {
        return this.XOffset;
    }
    
    public void setXOffset(Double XOffset) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("XOffset", this.XOffset, this.XOffset = XOffset);
        else
            this.XOffset = XOffset;
    }


    
    @Column(name="`YOFFSET`", nullable=false, precision=64, scale=0)
    public Double getYOffset() {
        return this.YOffset;
    }
    
    public void setYOffset(Double YOffset) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("YOffset", this.YOffset, this.YOffset = YOffset);
        else
            this.YOffset = YOffset;
    }


    
    @Column(name="`ZOFFSET`", nullable=false, precision=64, scale=0)
    public Double getZOffset() {
        return this.ZOffset;
    }
    
    public void setZOffset(Double ZOffset) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("ZOffset", this.ZOffset, this.ZOffset = ZOffset);
        else
            this.ZOffset = ZOffset;
    }


    
    @Column(name="`LOOFFSETTINGINDEX`", nullable=false)
    public Integer getLOOffsettingIndex() {
        return this.LOOffsettingIndex;
    }
    
    public void setLOOffsettingIndex(Integer LOOffsettingIndex) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("LOOffsettingIndex", this.LOOffsettingIndex, this.LOOffsettingIndex = LOOffsettingIndex);
        else
            this.LOOffsettingIndex = LOOffsettingIndex;
    }


    
    @Column(name="`WALSHSEQ`", nullable=false)
    public Integer getWalshSeq() {
        return this.walshSeq;
    }
    
    public void setWalshSeq(Integer walshSeq) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("walshSeq", this.walshSeq, this.walshSeq = walshSeq);
        else
            this.walshSeq = walshSeq;
    }


    
    @Column(name="`CAIBASELINE`")
    public Integer getCaiBaseline() {
        return this.caiBaseline;
    }
    
    public void setCaiBaseline(Integer caiBaseline) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("caiBaseline", this.caiBaseline, this.caiBaseline = caiBaseline);
        else
            this.caiBaseline = caiBaseline;
    }


    
    @Column(name="`CAIACA`")
    public Integer getCaiAca() {
        return this.caiAca;
    }
    
    public void setCaiAca(Integer caiAca) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("caiAca", this.caiAca, this.caiAca = caiAca);
        else
            this.caiAca = caiAca;
    }





}


