package alma.acs.tmcdb;
// Generated Jun 5, 2017 7:15:51 PM by Hibernate Tools 4.3.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BL_AcaCorrDelays generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="`BL_ACACORRDELAYS`"
)
public class BL_AcaCorrDelays extends alma.acs.tmcdb.translator.TmcdbObject implements java.io.Serializable {


     protected BL_AcaCorrDelaysId id;
     protected String who;
     protected String changeDesc;
     protected Double bbOneDelay;
     protected Double bbTwoDelay;
     protected Double bbThreeDelay;
     protected Double bbFourDelay;

    public BL_AcaCorrDelays() {
    }
   
       @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="`version`", column=@Column(name="VERSION`", nullable=false) ), 
        @AttributeOverride(name="modTime`", column=@Column(name="MODTIME`", nullable=false) ), 
        @AttributeOverride(name="operation`", column=@Column(name="OPERATION`", nullable=false, length=1) ), 
        @AttributeOverride(name="antennaId`", column=@Column(name="ANTENNAID`", nullable=false) ) } )
    public BL_AcaCorrDelaysId getId() {
        return this.id;
    }
    
    public void setId(BL_AcaCorrDelaysId id) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("id", this.id, this.id = id);
        else
            this.id = id;
    }


    
    @Column(name="`WHO`", length=128)
    public String getWho() {
        return this.who;
    }
    
    public void setWho(String who) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("who", this.who, this.who = who);
        else
            this.who = who;
    }


    
    @Column(name="`CHANGEDESC`", length=16777216)
    public String getChangeDesc() {
        return this.changeDesc;
    }
    
    public void setChangeDesc(String changeDesc) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("changeDesc", this.changeDesc, this.changeDesc = changeDesc);
        else
            this.changeDesc = changeDesc;
    }


    
    @Column(name="`BBONEDELAY`", nullable=false, precision=64, scale=0)
    public Double getBbOneDelay() {
        return this.bbOneDelay;
    }
    
    public void setBbOneDelay(Double bbOneDelay) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("bbOneDelay", this.bbOneDelay, this.bbOneDelay = bbOneDelay);
        else
            this.bbOneDelay = bbOneDelay;
    }


    
    @Column(name="`BBTWODELAY`", nullable=false, precision=64, scale=0)
    public Double getBbTwoDelay() {
        return this.bbTwoDelay;
    }
    
    public void setBbTwoDelay(Double bbTwoDelay) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("bbTwoDelay", this.bbTwoDelay, this.bbTwoDelay = bbTwoDelay);
        else
            this.bbTwoDelay = bbTwoDelay;
    }


    
    @Column(name="`BBTHREEDELAY`", nullable=false, precision=64, scale=0)
    public Double getBbThreeDelay() {
        return this.bbThreeDelay;
    }
    
    public void setBbThreeDelay(Double bbThreeDelay) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("bbThreeDelay", this.bbThreeDelay, this.bbThreeDelay = bbThreeDelay);
        else
            this.bbThreeDelay = bbThreeDelay;
    }


    
    @Column(name="`BBFOURDELAY`", nullable=false, precision=64, scale=0)
    public Double getBbFourDelay() {
        return this.bbFourDelay;
    }
    
    public void setBbFourDelay(Double bbFourDelay) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("bbFourDelay", this.bbFourDelay, this.bbFourDelay = bbFourDelay);
        else
            this.bbFourDelay = bbFourDelay;
    }





}


