package alma.acs.tmcdb;
// Generated Jun 5, 2017 7:15:51 PM by Hibernate Tools 4.3.1.Final


import alma.hibernate.util.StringEnumUserType;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

/**
 * BL_FocusModelCoeffOffset generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="`BL_FOCUSMODELCOEFFOFFSET`"
)
@TypeDefs({
@TypeDef(name="BL_AntennaFMCoeffOffBand", typeClass=StringEnumUserType.class,
   parameters={ @Parameter(name="enumClassName", value="alma.acs.tmcdb.BL_AntennaFMCoeffOffBand") }),
@TypeDef(name="BL_AntennaFMCoeffOffOp", typeClass=StringEnumUserType.class,
   parameters={ @Parameter(name="enumClassName", value="alma.acs.tmcdb.BL_AntennaFMCoeffOffOp") })
})
public class BL_FocusModelCoeffOffset extends alma.acs.tmcdb.translator.TmcdbObject implements java.io.Serializable {


     protected BL_FocusModelCoeffOffsetId id;
     protected String who;
     protected String changeDesc;
     protected Double offset;

    public BL_FocusModelCoeffOffset() {
    }
   
       @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="`version`", column=@Column(name="VERSION`", nullable=false) ), 
        @AttributeOverride(name="modTime`", column=@Column(name="MODTIME`", nullable=false) ), 
        @AttributeOverride(name="operation`", column=@Column(name="OPERATION`", nullable=false, length=1) ), 
        @AttributeOverride(name="focusModelId`", column=@Column(name="FOCUSMODELID`", nullable=false) ), 
        @AttributeOverride(name="coeffName`", column=@Column(name="COEFFNAME`", nullable=false, length=128) ), 
        @AttributeOverride(name="receiverBand`", column=@Column(name="RECEIVERBAND`", nullable=false, length=128) ) } )
    public BL_FocusModelCoeffOffsetId getId() {
        return this.id;
    }
    
    public void setId(BL_FocusModelCoeffOffsetId id) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("id", this.id, this.id = id);
        else
            this.id = id;
    }


    
    @Column(name="`WHO`", length=128)
    public String getWho() {
        return this.who;
    }
    
    public void setWho(String who) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("who", this.who, this.who = who);
        else
            this.who = who;
    }


    
    @Column(name="`CHANGEDESC`", length=16777216)
    public String getChangeDesc() {
        return this.changeDesc;
    }
    
    public void setChangeDesc(String changeDesc) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("changeDesc", this.changeDesc, this.changeDesc = changeDesc);
        else
            this.changeDesc = changeDesc;
    }


    
    @Column(name="`OFFSET`", nullable=false, precision=64, scale=0)
    public Double getOffset() {
        return this.offset;
    }
    
    public void setOffset(Double offset) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("offset", this.offset, this.offset = offset);
        else
            this.offset = offset;
    }





}


