package alma.acs.tmcdb;
// Generated Jun 5, 2017 7:15:51 PM by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CorrStationBin generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="`CORRSTATIONBIN`"
)
public class CorrStationBin extends alma.acs.tmcdb.translator.TmcdbObject implements java.io.Serializable {


     protected Integer baseElementId;
     protected BaseElement baseElement;
     protected CorrQuadrantRack corrQuadrantRack;
     protected String stationBinName;

    public CorrStationBin() {
    }
   
       @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="baseElement"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="`BASEELEMENTID`", unique=true, nullable=false)
    public Integer getBaseElementId() {
        return this.baseElementId;
    }
    
    public void setBaseElementId(Integer baseElementId) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("baseElementId", this.baseElementId, this.baseElementId = baseElementId);
        else
            this.baseElementId = baseElementId;
    }


@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public BaseElement getBaseElement() {
        return this.baseElement;
    }
    
    public void setBaseElement(BaseElement baseElement) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("baseElement", this.baseElement, this.baseElement = baseElement);
        else
            this.baseElement = baseElement;
    }


@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="`CORRQUADRANTRACKID`", nullable=false)
    public CorrQuadrantRack getCorrQuadrantRack() {
        return this.corrQuadrantRack;
    }
    
    public void setCorrQuadrantRack(CorrQuadrantRack corrQuadrantRack) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("corrQuadrantRack", this.corrQuadrantRack, this.corrQuadrantRack = corrQuadrantRack);
        else
            this.corrQuadrantRack = corrQuadrantRack;
    }


    
    @Column(name="`STATIONBINNAME`", nullable=false, length=128)
    public String getStationBinName() {
        return this.stationBinName;
    }
    
    public void setStationBinName(String stationBinName) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("stationBinName", this.stationBinName, this.stationBinName = stationBinName);
        else
            this.stationBinName = stationBinName;
    }





}


