package alma.acs.tmcdb;
// Generated Jun 5, 2017 7:15:51 PM by Hibernate Tools 4.3.1.Final


import alma.hibernate.util.StringEnumUserType;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.TypeDef;

/**
 * FocusModelCoeffOffset generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="`FOCUSMODELCOEFFOFFSET`"
)
@TypeDef(name="AntennaFMCoeffOffBand", typeClass=StringEnumUserType.class,
   parameters={ @Parameter(name="enumClassName", value="alma.acs.tmcdb.AntennaFMCoeffOffBand") })
public class FocusModelCoeffOffset extends alma.acs.tmcdb.translator.TmcdbObject implements java.io.Serializable {


     protected FocusModelCoeffOffsetId id;
     protected FocusModelCoeff focusModelCoeff;
     protected Double offset;

    public FocusModelCoeffOffset() {
    }
   
       @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="`focusModelCoeffId`", column=@Column(name="FOCUSMODELCOEFFID`", nullable=false) ), 
        @AttributeOverride(name="receiverBand`", column=@Column(name="RECEIVERBAND`", nullable=false, length=128) ) } )
    public FocusModelCoeffOffsetId getId() {
        return this.id;
    }
    
    public void setId(FocusModelCoeffOffsetId id) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("id", this.id, this.id = id);
        else
            this.id = id;
    }


@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="`FOCUSMODELCOEFFID`", nullable=false, insertable=false, updatable=false)
    public FocusModelCoeff getFocusModelCoeff() {
        return this.focusModelCoeff;
    }
    
    public void setFocusModelCoeff(FocusModelCoeff focusModelCoeff) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("focusModelCoeff", this.focusModelCoeff, this.focusModelCoeff = focusModelCoeff);
        else
            this.focusModelCoeff = focusModelCoeff;
    }


    
    @Column(name="`OFFSET`", nullable=false, precision=64, scale=0)
    public Double getOffset() {
        return this.offset;
    }
    
    public void setOffset(Double offset) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("offset", this.offset, this.offset = offset);
        else
            this.offset = offset;
    }





}


