package alma.acs.tmcdb;
// Generated Jun 5, 2017 7:15:51 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LRUType generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="`LRUTYPE`"
)
public class LRUType extends alma.acs.tmcdb.translator.TmcdbObject implements java.io.Serializable {


     protected String LRUName;
     protected String fullName;
     protected String ICD;
     protected Long ICDDate;
     protected String description;
     protected String notes;
     private Set<AssemblyType> assemblyTypes = new HashSet<AssemblyType>(0);

    public LRUType() {
    }
   
       @Id 

    
    @Column(name="`LRUNAME`", unique=true, nullable=false, length=128)
    public String getLRUName() {
        return this.LRUName;
    }
    
    public void setLRUName(String LRUName) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("LRUName", this.LRUName, this.LRUName = LRUName);
        else
            this.LRUName = LRUName;
    }


    
    @Column(name="`FULLNAME`", nullable=false, length=256)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("fullName", this.fullName, this.fullName = fullName);
        else
            this.fullName = fullName;
    }


    
    @Column(name="`ICD`", nullable=false, length=256)
    public String getICD() {
        return this.ICD;
    }
    
    public void setICD(String ICD) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("ICD", this.ICD, this.ICD = ICD);
        else
            this.ICD = ICD;
    }


    
    @Column(name="`ICDDATE`", nullable=false)
    public Long getICDDate() {
        return this.ICDDate;
    }
    
    public void setICDDate(Long ICDDate) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("ICDDate", this.ICDDate, this.ICDDate = ICDDate);
        else
            this.ICDDate = ICDDate;
    }


    
    @Column(name="`DESCRIPTION`", nullable=false, length=16777216)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("description", this.description, this.description = description);
        else
            this.description = description;
    }


    
    @Column(name="`NOTES`", length=16777216)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("notes", this.notes, this.notes = notes);
        else
            this.notes = notes;
    }


@OneToMany(fetch=FetchType.LAZY, mappedBy="LRUType")
    public Set<AssemblyType> getAssemblyTypes() {
        return this.assemblyTypes;
    }
    
    public void setAssemblyTypes(Set<AssemblyType> assemblyTypes) {    
    	this.assemblyTypes = assemblyTypes;
    }

	public void addAssemblyTypes(Set<AssemblyType> elements) {
		if( this.assemblyTypes != null )
			for(Iterator<AssemblyType> it = elements.iterator(); it.hasNext(); )
				addAssemblyTypeToAssemblyTypes((AssemblyType)it.next());
	}

	public void addAssemblyTypeToAssemblyTypes(AssemblyType element) {
		if( !this.assemblyTypes.contains(element) ) {
			this.assemblyTypes.add(element);
		}
	}





}


