package alma.acs.tmcdb;
// Generated Jun 5, 2017 7:15:51 PM by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PointingModelCoeffOffsetId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class PointingModelCoeffOffsetId  implements java.io.Serializable {


     private Integer pointingModelCoeffId;
     private AntennaPMCoeffOffBand receiverBand;

    public PointingModelCoeffOffsetId() {
    }
   


    @Column(name="`POINTINGMODELCOEFFID`", nullable=false)
    public Integer getPointingModelCoeffId() {
        return this.pointingModelCoeffId;
    }
    
    public void setPointingModelCoeffId(Integer pointingModelCoeffId) {    
    	this.pointingModelCoeffId = pointingModelCoeffId;
    }



    @Column(name="`RECEIVERBAND`", nullable=false, length=128)
    public AntennaPMCoeffOffBand getReceiverBand() {
        return this.receiverBand;
    }
    
    public void setReceiverBand(AntennaPMCoeffOffBand receiverBand) {    
    	this.receiverBand = receiverBand;
    }



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PointingModelCoeffOffsetId) ) return false;
		 PointingModelCoeffOffsetId castOther = ( PointingModelCoeffOffsetId ) other;

		 return ( (this.getPointingModelCoeffId()==castOther.getPointingModelCoeffId()) || ( this.getPointingModelCoeffId()!=null && castOther.getPointingModelCoeffId()!=null && this.getPointingModelCoeffId().equals(castOther.getPointingModelCoeffId()) ) )
 && ( (this.getReceiverBand()==castOther.getReceiverBand()) || ( this.getReceiverBand()!=null && castOther.getReceiverBand()!=null && this.getReceiverBand().equals(castOther.getReceiverBand()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getPointingModelCoeffId() == null ? 0 : this.getPointingModelCoeffId().hashCode() );
         result = 37 * result + ( getReceiverBand() == null ? 0 : this.getReceiverBand().hashCode() );
         return result;
   }


}


