package alma.acs.tmcdb;
// Generated Jun 5, 2017 7:15:51 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Startup generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="`STARTUP`"
    , uniqueConstraints =  @UniqueConstraint(columnNames={"`STARTUPNAME`", "`CONFIGURATIONID`"})
)
public class Startup extends alma.acs.tmcdb.translator.TmcdbObject implements java.io.Serializable {


     protected Integer startupId;
     protected HWConfiguration HWConfiguration;
     protected String startupName;
     private Set<BaseElementStartup> baseElementStartups = new HashSet<BaseElementStartup>(0);

    public Startup() {
    }
   
    @Id @GeneratedValue(generator="generator")
    @GenericGenerator(name="generator", strategy="native",
       parameters = {@Parameter(name="sequence", value="Startup_seq")}
	)

    
    @Column(name="`STARTUPID`", unique=true, nullable=false)
    public Integer getStartupId() {
        return this.startupId;
    }
    
    public void setStartupId(Integer startupId) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("startupId", this.startupId, this.startupId = startupId);
        else
            this.startupId = startupId;
    }


@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="`CONFIGURATIONID`", nullable=false)
    public HWConfiguration getHWConfiguration() {
        return this.HWConfiguration;
    }
    
    public void setHWConfiguration(HWConfiguration HWConfiguration) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("HWConfiguration", this.HWConfiguration, this.HWConfiguration = HWConfiguration);
        else
            this.HWConfiguration = HWConfiguration;
    }


    
    @Column(name="`STARTUPNAME`", nullable=false, length=256)
    public String getStartupName() {
        return this.startupName;
    }
    
    public void setStartupName(String startupName) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("startupName", this.startupName, this.startupName = startupName);
        else
            this.startupName = startupName;
    }


@OneToMany(fetch=FetchType.LAZY, mappedBy="startup")
    public Set<BaseElementStartup> getBaseElementStartups() {
        return this.baseElementStartups;
    }
    
    public void setBaseElementStartups(Set<BaseElementStartup> baseElementStartups) {    
    	this.baseElementStartups = baseElementStartups;
    }

	public void addBaseElementStartups(Set<BaseElementStartup> elements) {
		if( this.baseElementStartups != null )
			for(Iterator<BaseElementStartup> it = elements.iterator(); it.hasNext(); )
				addBaseElementStartupToBaseElementStartups((BaseElementStartup)it.next());
	}

	public void addBaseElementStartupToBaseElementStartups(BaseElementStartup element) {
		if( !this.baseElementStartups.contains(element) ) {
			this.baseElementStartups.add(element);
		}
	}



   public boolean equalsContent(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Startup) ) return false;
		 Startup castOther = ( Startup ) other;

		 return ( (this.getHWConfiguration()==castOther.getHWConfiguration()) || ( this.getHWConfiguration()!=null && castOther.getHWConfiguration()!=null && this.getHWConfiguration().equals(castOther.getHWConfiguration()) ) )
 && ( (this.getStartupName()==castOther.getStartupName()) || ( this.getStartupName()!=null && castOther.getStartupName()!=null && this.getStartupName().equals(castOther.getStartupName()) ) );
   }

   public int hashCodeContent() {
         int result = 17;

         
         result = 37 * result + ( getHWConfiguration() == null ? 0 : this.getHWConfiguration().hashCode() );
         result = 37 * result + ( getStartupName() == null ? 0 : this.getStartupName().hashCode() );
         
         return result;
   }


}


