package alma.acs.tmcdb;
// Generated Jun 5, 2017 7:15:51 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * WeatherStationController generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="`WEATHERSTATIONCONTROLLER`"
)
public class WeatherStationController extends alma.acs.tmcdb.translator.TmcdbObject implements java.io.Serializable {


     protected Integer baseElementId;
     protected BaseElement baseElement;
     protected Long commissionDate;
     private Set<WeatherStationToPad> weatherStationToPads = new HashSet<WeatherStationToPad>(0);

    public WeatherStationController() {
    }
   
       @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="baseElement"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="`BASEELEMENTID`", unique=true, nullable=false)
    public Integer getBaseElementId() {
        return this.baseElementId;
    }
    
    public void setBaseElementId(Integer baseElementId) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("baseElementId", this.baseElementId, this.baseElementId = baseElementId);
        else
            this.baseElementId = baseElementId;
    }


@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public BaseElement getBaseElement() {
        return this.baseElement;
    }
    
    public void setBaseElement(BaseElement baseElement) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("baseElement", this.baseElement, this.baseElement = baseElement);
        else
            this.baseElement = baseElement;
    }


    
    @Column(name="`COMMISSIONDATE`", nullable=false)
    public Long getCommissionDate() {
        return this.commissionDate;
    }
    
    public void setCommissionDate(Long commissionDate) {    
        if( propertyChangeSupport != null )
            propertyChangeSupport.firePropertyChange("commissionDate", this.commissionDate, this.commissionDate = commissionDate);
        else
            this.commissionDate = commissionDate;
    }


@OneToMany(fetch=FetchType.LAZY, mappedBy="weatherStationController")
    public Set<WeatherStationToPad> getWeatherStationToPads() {
        return this.weatherStationToPads;
    }
    
    public void setWeatherStationToPads(Set<WeatherStationToPad> weatherStationToPads) {    
    	this.weatherStationToPads = weatherStationToPads;
    }

	public void addWeatherStationToPads(Set<WeatherStationToPad> elements) {
		if( this.weatherStationToPads != null )
			for(Iterator<WeatherStationToPad> it = elements.iterator(); it.hasNext(); )
				addWeatherStationToPadToWeatherStationToPads((WeatherStationToPad)it.next());
	}

	public void addWeatherStationToPadToWeatherStationToPads(WeatherStationToPad element) {
		if( !this.weatherStationToPads.contains(element) ) {
			this.weatherStationToPads.add(element);
		}
	}





}


