#!/bin/bash
#A general purpose script designed to be used as the prologue
#for most tat modular tests

#Set the CDB to be the present working directory IFF
#it's set to be the default ACS CDB
if [ "$ACS_CDB" = "$ACSDATA/config/defaultCDB" ] || [ "$ACS_CDB" = "" ]
then
    ACS_CDB=$PWD
fi 

#Start the services and manager
echo " Starting ORB Services and Manager"
acsStart > $ACS_TMP/acsStart.log

#Get the ACS_INSTANCE from the log file just written out
export ACS_INSTANCE=`grep -m 1 "For this ACS session, please do an" $ACS_TMP/acsStart.log | cut -d\' -f2 | cut -d= -f2`
if [ "$ACS_INSTANCE" = "" ]
then
    echo "Could not determine whether an ACS_INSTANCE was selected by acsStart!"
    echo "Exiting!"
    exit 1
else 
    echo $ACS_INSTANCE > $ACS_TMP/acs_instance
fi

#
# Checks LOGGING mode
#

if [ x"$1" = x"-l" ]
then
# commands from a simplified "accStarter -p loggingClient.pid -o all_logs.xml loggingClient LoggingChannel"
    
    pidfile=$ACS_TMP/loggingClient.pid
    outfile=$ACS_TMP/all_logs.xml
	
	# logging client writes to stderr which would confuse TAT
	loggingClient LoggingChannel > $outfile 2>$ACS_TMP/logerrfile.out &
	pid=$!

	## store pid in file, so that acsutilTATEpilogue can kill the logging client process (there's no other way to end it)
	echo $pid >> $pidfile
fi
