#! /bin/bash

export ACS_TMP=$PWD/tmp
export ACS_LOG_STDOUT=4
export MACI_RECOVERY_FILE_NAME=$ACS_TMP/maciRecovery
export ACS_BACI_RECOVERY_FILE=$ACS_TMP/baciRecovery
export ACS_LOG_FILE=$ACS_TMP/log_cache.dat


#
# ___oOo___

