#ifndef _TEST_TEMPERATURE_DATA_BLOCK_EVENT
#define _TEST_TEMPERATURE_DATA_BLOCK_EVENT

module TESTFRIDGE
{
   enum temperatureStatus { OVERREF, ATREF, BELOWREF };

#pragma DCPS_DATA_TYPE "TESTFRIDGE::temperatureDataBlockEvent"

   struct temperatureDataBlockEvent
   {
      long key;
      float absolutDiff;
      temperatureStatus status;
   };
};

#endif 
