#!/bin/bash

if [ ! -d $ACS_TMP ]
then
        mkdir $ACS_TMP
fi


acsutilTATPrologue

export INTROOT="$HOME/introot"
export DDS_ROOT=/alma/ACS-8.0/DDS/build/linux
export PATH=$PATH:$DDS_ROOT/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DDS_ROOT/lib
export DDS_TYPE=OPEN_DDS
export ACS_CDB=$PWD

acsStartContainer -cpp Container &> $ACS_TMP/container.log &
sleep 5
startDCPSInfoRepo &> $ACS_TMP/InfoRepo.log &
sleep 2
