/*
ALMA - Atacama Large Millimiter Array
* Copyright (c) European Southern Observatory, 2014 
* 
* This library is free software; you can redistribute it and/or
* modify it under the terms of the GNU Lesser General Public
* License as published by the Free Software Foundation; either
* version 2.1 of the License, or (at your option) any later version.
* 
* This library is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* Lesser General Public License for more details.
* 
* You should have received a copy of the GNU Lesser General Public
* License along with this library; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 
 * @author  acaproni
 * @since   2014.6
 */
package alma.acs.util.stringqueue;

/**
 * The exception generated by the queue of strings.
 */
public class StringQueueException extends Exception {

	public StringQueueException() {
		super();
	}

	public StringQueueException(String message) {
		super(message);
	}

	public StringQueueException(String message, Throwable cause) {
		super(message, cause);
	}

	public StringQueueException(Throwable cause) {
		super(cause);
	}

}